/* Copyright (c) 2015, Oracle and/or its affiliates. All rights reserved */
package oracle.cloud.sampleaapps.leadcapturesys.model;


import oracle.jbo.RowSet;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Apr 14 15:23:02 CEST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LeadCaptureSysNewActivityIdVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        MaxActivityId1 {
            public Object get(LeadCaptureSysNewActivityIdVORowImpl obj) {
                return obj.getMaxActivityId1();
            }

            public void put(LeadCaptureSysNewActivityIdVORowImpl obj,
                            Object value) {
                obj.setMaxActivityId1((Number)value);
            }
        }
        ,
        LeadCaptureSysVO1 {
            public Object get(LeadCaptureSysNewActivityIdVORowImpl obj) {
                return obj.getLeadCaptureSysVO1();
            }

            public void put(LeadCaptureSysNewActivityIdVORowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(LeadCaptureSysNewActivityIdVORowImpl object);

        public abstract void put(LeadCaptureSysNewActivityIdVORowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int MAXACTIVITYID1 = AttributesEnum.MaxActivityId1.index();
    public static final int LEADCAPTURESYSVO1 = AttributesEnum.LeadCaptureSysVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public LeadCaptureSysNewActivityIdVORowImpl() {
    }


    /**
     * Gets the attribute value for the calculated attribute MaxActivityId1.
     * @return the MaxActivityId1
     */
    public Number getMaxActivityId1() {
        return (Number) getAttributeInternal(MAXACTIVITYID1);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MaxActivityId1.
     * @param value value to set the  MaxActivityId1
     */
    public void setMaxActivityId1(Number value) {
        setAttributeInternal(MAXACTIVITYID1, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LeadCaptureSysVO1.
     */
    public RowSet getLeadCaptureSysVO1() {
        return (RowSet)getAttributeInternal(LEADCAPTURESYSVO1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
