package com.oracle.ptsdemo.oscproxyclient;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.jws.soap.SOAPBinding.Style;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebService(wsdlLocation="https://my-oraclesalescloud.com/opptyMgmtOpportunities/OpportunityService?wsdl",
  targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/",
  name="OpportunityService")
@XmlSeeAlso(
  { com.oracle.ptsdemo.oscproxyclient.types.ObjectFactory.class })
@SOAPBinding(style=Style.DOCUMENT, parameterStyle=ParameterStyle.BARE)
public interface OpportunityService
{
  @WebMethod(action="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/getOpportunity")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/getOpportunity", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/OpportunityService/getOpportunity/Fault/ServiceException",
          className=com.oracle.ptsdemo.oscproxyclient.ServiceException.class) },
    output="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/OpportunityService/getOpportunityResponse")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
    partName="parameters", name="getOpportunityResponse")
  public com.oracle.ptsdemo.oscproxyclient.types.GetOpportunityResponse getOpportunity(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
      partName="parameters", name="getOpportunity")
    com.oracle.ptsdemo.oscproxyclient.types.GetOpportunity parameters)
    throws com.oracle.ptsdemo.oscproxyclient.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/createOpportunity")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/createOpportunity", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/OpportunityService/createOpportunity/Fault/ServiceException",
          className=com.oracle.ptsdemo.oscproxyclient.ServiceException.class) },
    output="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/OpportunityService/createOpportunityResponse")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
    partName="parameters", name="createOpportunityResponse")
  public com.oracle.ptsdemo.oscproxyclient.types.CreateOpportunityResponse createOpportunity(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
      partName="parameters", name="createOpportunity")
    com.oracle.ptsdemo.oscproxyclient.types.CreateOpportunity parameters)
    throws com.oracle.ptsdemo.oscproxyclient.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/updateOpportunity")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/updateOpportunity", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/OpportunityService/updateOpportunity/Fault/ServiceException",
          className=com.oracle.ptsdemo.oscproxyclient.ServiceException.class) },
    output="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/OpportunityService/updateOpportunityResponse")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
    partName="parameters", name="updateOpportunityResponse")
  public com.oracle.ptsdemo.oscproxyclient.types.UpdateOpportunityResponse updateOpportunity(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
      partName="parameters", name="updateOpportunity")
    com.oracle.ptsdemo.oscproxyclient.types.UpdateOpportunity parameters)
    throws com.oracle.ptsdemo.oscproxyclient.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunity")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunity", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/OpportunityService/deleteOpportunity/Fault/ServiceException",
          className=com.oracle.ptsdemo.oscproxyclient.ServiceException.class) },
    output="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/OpportunityService/deleteOpportunityResponse")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
    partName="parameters", name="deleteOpportunityResponse")
  public com.oracle.ptsdemo.oscproxyclient.types.DeleteOpportunityResponse deleteOpportunity(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
      partName="parameters", name="deleteOpportunity")
    com.oracle.ptsdemo.oscproxyclient.types.DeleteOpportunity parameters)
    throws com.oracle.ptsdemo.oscproxyclient.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/mergeOpportunity")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/mergeOpportunity", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/OpportunityService/mergeOpportunity/Fault/ServiceException",
          className=com.oracle.ptsdemo.oscproxyclient.ServiceException.class) },
    output="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/OpportunityService/mergeOpportunityResponse")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
    partName="parameters", name="mergeOpportunityResponse")
  public com.oracle.ptsdemo.oscproxyclient.types.MergeOpportunityResponse mergeOpportunity(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
      partName="parameters", name="mergeOpportunity")
    com.oracle.ptsdemo.oscproxyclient.types.MergeOpportunity parameters)
    throws com.oracle.ptsdemo.oscproxyclient.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/processOpportunity")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/processOpportunity", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/OpportunityService/processOpportunity/Fault/ServiceException",
          className=com.oracle.ptsdemo.oscproxyclient.ServiceException.class) },
    output="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/OpportunityService/processOpportunityResponse")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
    partName="parameters", name="processOpportunityResponse")
  public com.oracle.ptsdemo.oscproxyclient.types.ProcessOpportunityResponse processOpportunity(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
      partName="parameters", name="processOpportunity")
    com.oracle.ptsdemo.oscproxyclient.types.ProcessOpportunity parameters)
    throws com.oracle.ptsdemo.oscproxyclient.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/processCSOpportunity")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/processCSOpportunity", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/OpportunityService/processCSOpportunity/Fault/ServiceException",
          className=com.oracle.ptsdemo.oscproxyclient.ServiceException.class) },
    output="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/OpportunityService/processCSOpportunityResponse")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
    partName="parameters", name="processCSOpportunityResponse")
  public com.oracle.ptsdemo.oscproxyclient.types.ProcessCSOpportunityResponse processCSOpportunity(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
      partName="parameters", name="processCSOpportunity")
    com.oracle.ptsdemo.oscproxyclient.types.ProcessCSOpportunity parameters)
    throws com.oracle.ptsdemo.oscproxyclient.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/processCSOpportunityAsync")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/processCSOpportunityAsync")
  @Oneway
  public void processCSOpportunityAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
      partName="parameters", name="processCSOpportunityAsync")
    com.oracle.ptsdemo.oscproxyclient.types.ProcessCSOpportunityAsync parameters);

  @WebMethod(action="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/processOpportunityAsync")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/processOpportunityAsync")
  @Oneway
  public void processOpportunityAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
      partName="parameters", name="processOpportunityAsync")
    com.oracle.ptsdemo.oscproxyclient.types.ProcessOpportunityAsync parameters);

  @WebMethod(action="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunityAsync")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunityAsync")
  @Oneway
  public void deleteOpportunityAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
      partName="parameters", name="deleteOpportunityAsync")
    com.oracle.ptsdemo.oscproxyclient.types.DeleteOpportunityAsync parameters);

  @WebMethod(action="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/getOpportunityAsync")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/getOpportunityAsync")
  @Oneway
  public void getOpportunityAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
      partName="parameters", name="getOpportunityAsync")
    com.oracle.ptsdemo.oscproxyclient.types.GetOpportunityAsync parameters);

  @WebMethod(action="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/createOpportunityAsync")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/createOpportunityAsync")
  @Oneway
  public void createOpportunityAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
      partName="parameters", name="createOpportunityAsync")
    com.oracle.ptsdemo.oscproxyclient.types.CreateOpportunityAsync parameters);

  @WebMethod(action="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/mergeOpportunityAsync")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/mergeOpportunityAsync")
  @Oneway
  public void mergeOpportunityAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
      partName="parameters", name="mergeOpportunityAsync")
    com.oracle.ptsdemo.oscproxyclient.types.MergeOpportunityAsync parameters);

  @WebMethod(action="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/updateOpportunityAsync")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/updateOpportunityAsync")
  @Oneway
  public void updateOpportunityAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
      partName="parameters", name="updateOpportunityAsync")
    com.oracle.ptsdemo.oscproxyclient.types.UpdateOpportunityAsync parameters);

  @WebMethod(action="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunityCompetitor")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunityCompetitor", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/OpportunityService/deleteOpportunityCompetitor/Fault/ServiceException",
          className=com.oracle.ptsdemo.oscproxyclient.ServiceException.class) },
    output="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/OpportunityService/deleteOpportunityCompetitorResponse")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
    partName="parameters", name="deleteOpportunityCompetitorResponse")
  public com.oracle.ptsdemo.oscproxyclient.types.DeleteOpportunityCompetitorResponse deleteOpportunityCompetitor(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
      partName="parameters", name="deleteOpportunityCompetitor")
    com.oracle.ptsdemo.oscproxyclient.types.DeleteOpportunityCompetitor parameters)
    throws com.oracle.ptsdemo.oscproxyclient.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunityLead")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunityLead", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/OpportunityService/deleteOpportunityLead/Fault/ServiceException",
          className=com.oracle.ptsdemo.oscproxyclient.ServiceException.class) },
    output="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/OpportunityService/deleteOpportunityLeadResponse")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
    partName="parameters", name="deleteOpportunityLeadResponse")
  public com.oracle.ptsdemo.oscproxyclient.types.DeleteOpportunityLeadResponse deleteOpportunityLead(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
      partName="parameters", name="deleteOpportunityLead")
    com.oracle.ptsdemo.oscproxyclient.types.DeleteOpportunityLead parameters)
    throws com.oracle.ptsdemo.oscproxyclient.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunityReference")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunityReference", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/OpportunityService/deleteOpportunityReference/Fault/ServiceException",
          className=com.oracle.ptsdemo.oscproxyclient.ServiceException.class) },
    output="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/OpportunityService/deleteOpportunityReferenceResponse")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
    partName="parameters", name="deleteOpportunityReferenceResponse")
  public com.oracle.ptsdemo.oscproxyclient.types.DeleteOpportunityReferenceResponse deleteOpportunityReference(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
      partName="parameters", name="deleteOpportunityReference")
    com.oracle.ptsdemo.oscproxyclient.types.DeleteOpportunityReference parameters)
    throws com.oracle.ptsdemo.oscproxyclient.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunityResource")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunityResource", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/OpportunityService/deleteOpportunityResource/Fault/ServiceException",
          className=com.oracle.ptsdemo.oscproxyclient.ServiceException.class) },
    output="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/OpportunityService/deleteOpportunityResourceResponse")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
    partName="parameters", name="deleteOpportunityResourceResponse")
  public com.oracle.ptsdemo.oscproxyclient.types.DeleteOpportunityResourceResponse deleteOpportunityResource(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
      partName="parameters", name="deleteOpportunityResource")
    com.oracle.ptsdemo.oscproxyclient.types.DeleteOpportunityResource parameters)
    throws com.oracle.ptsdemo.oscproxyclient.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunityMktResponse")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunityMktResponse", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/OpportunityService/deleteOpportunityMktResponse/Fault/ServiceException",
          className=com.oracle.ptsdemo.oscproxyclient.ServiceException.class) },
    output="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/OpportunityService/deleteOpportunityMktResponseResponse")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
    partName="parameters", name="deleteOpportunityMktResponseResponse")
  public com.oracle.ptsdemo.oscproxyclient.types.DeleteOpportunityMktResponseResponse deleteOpportunityMktResponse(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
      partName="parameters", name="deleteOpportunityMktResponse")
    com.oracle.ptsdemo.oscproxyclient.types.DeleteOpportunityMktResponse parameters)
    throws com.oracle.ptsdemo.oscproxyclient.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunityRevenue")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunityRevenue", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/OpportunityService/deleteOpportunityRevenue/Fault/ServiceException",
          className=com.oracle.ptsdemo.oscproxyclient.ServiceException.class) },
    output="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/OpportunityService/deleteOpportunityRevenueResponse")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
    partName="parameters", name="deleteOpportunityRevenueResponse")
  public com.oracle.ptsdemo.oscproxyclient.types.DeleteOpportunityRevenueResponse deleteOpportunityRevenue(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
      partName="parameters", name="deleteOpportunityRevenue")
    com.oracle.ptsdemo.oscproxyclient.types.DeleteOpportunityRevenue parameters)
    throws com.oracle.ptsdemo.oscproxyclient.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunitySource")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunitySource", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/OpportunityService/deleteOpportunitySource/Fault/ServiceException",
          className=com.oracle.ptsdemo.oscproxyclient.ServiceException.class) },
    output="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/OpportunityService/deleteOpportunitySourceResponse")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
    partName="parameters", name="deleteOpportunitySourceResponse")
  public com.oracle.ptsdemo.oscproxyclient.types.DeleteOpportunitySourceResponse deleteOpportunitySource(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
      partName="parameters", name="deleteOpportunitySource")
    com.oracle.ptsdemo.oscproxyclient.types.DeleteOpportunitySource parameters)
    throws com.oracle.ptsdemo.oscproxyclient.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunityCompetitorAsync")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunityCompetitorAsync")
  @Oneway
  public void deleteOpportunityCompetitorAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
      partName="parameters", name="deleteOpportunityCompetitorAsync")
    com.oracle.ptsdemo.oscproxyclient.types.DeleteOpportunityCompetitorAsync parameters);

  @WebMethod(action="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunityMktResponseAsync")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunityMktResponseAsync")
  @Oneway
  public void deleteOpportunityMktResponseAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
      partName="parameters", name="deleteOpportunityMktResponseAsync")
    com.oracle.ptsdemo.oscproxyclient.types.DeleteOpportunityMktResponseAsync parameters);

  @WebMethod(action="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunityRevenueAsync")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunityRevenueAsync")
  @Oneway
  public void deleteOpportunityRevenueAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
      partName="parameters", name="deleteOpportunityRevenueAsync")
    com.oracle.ptsdemo.oscproxyclient.types.DeleteOpportunityRevenueAsync parameters);

  @WebMethod(action="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunityResourceAsync")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunityResourceAsync")
  @Oneway
  public void deleteOpportunityResourceAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
      partName="parameters", name="deleteOpportunityResourceAsync")
    com.oracle.ptsdemo.oscproxyclient.types.DeleteOpportunityResourceAsync parameters);

  @WebMethod(action="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunityLeadAsync")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunityLeadAsync")
  @Oneway
  public void deleteOpportunityLeadAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
      partName="parameters", name="deleteOpportunityLeadAsync")
    com.oracle.ptsdemo.oscproxyclient.types.DeleteOpportunityLeadAsync parameters);

  @WebMethod(action="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunitySourceAsync")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunitySourceAsync")
  @Oneway
  public void deleteOpportunitySourceAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
      partName="parameters", name="deleteOpportunitySourceAsync")
    com.oracle.ptsdemo.oscproxyclient.types.DeleteOpportunitySourceAsync parameters);

  @WebMethod(action="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunityReferenceAsync")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunityReferenceAsync")
  @Oneway
  public void deleteOpportunityReferenceAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
      partName="parameters", name="deleteOpportunityReferenceAsync")
    com.oracle.ptsdemo.oscproxyclient.types.DeleteOpportunityReferenceAsync parameters);

  @WebMethod(action="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/doAutoAssignmentAsynchronously")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/doAutoAssignmentAsynchronously", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/OpportunityService/doAutoAssignmentAsynchronously/Fault/ServiceException",
          className=com.oracle.ptsdemo.oscproxyclient.ServiceException.class) },
    output="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/OpportunityService/doAutoAssignmentAsynchronouslyResponse")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
    partName="parameters", name="doAutoAssignmentAsynchronouslyResponse")
  public com.oracle.ptsdemo.oscproxyclient.types.DoAutoAssignmentAsynchronouslyResponse doAutoAssignmentAsynchronously(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
      partName="parameters", name="doAutoAssignmentAsynchronously")
    com.oracle.ptsdemo.oscproxyclient.types.DoAutoAssignmentAsynchronously parameters)
    throws com.oracle.ptsdemo.oscproxyclient.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/doAutoAssignmentAsynchronouslyAsync")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/doAutoAssignmentAsynchronouslyAsync")
  @Oneway
  public void doAutoAssignmentAsynchronouslyAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
      partName="parameters", name="doAutoAssignmentAsynchronouslyAsync")
    com.oracle.ptsdemo.oscproxyclient.types.DoAutoAssignmentAsynchronouslyAsync parameters);

  @WebMethod(action="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunityContact")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunityContact", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/OpportunityService/deleteOpportunityContact/Fault/ServiceException",
          className=com.oracle.ptsdemo.oscproxyclient.ServiceException.class) },
    output="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/OpportunityService/deleteOpportunityContactResponse")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
    partName="parameters", name="deleteOpportunityContactResponse")
  public com.oracle.ptsdemo.oscproxyclient.types.DeleteOpportunityContactResponse deleteOpportunityContact(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
      partName="parameters", name="deleteOpportunityContact")
    com.oracle.ptsdemo.oscproxyclient.types.DeleteOpportunityContact parameters)
    throws com.oracle.ptsdemo.oscproxyclient.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunityContactAsync")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunityContactAsync")
  @Oneway
  public void deleteOpportunityContactAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
      partName="parameters", name="deleteOpportunityContactAsync")
    com.oracle.ptsdemo.oscproxyclient.types.DeleteOpportunityContactAsync parameters);

  @WebMethod(action="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/findOpportunity")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/findOpportunity", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/OpportunityService/findOpportunity/Fault/ServiceException",
          className=com.oracle.ptsdemo.oscproxyclient.ServiceException.class) },
    output="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/OpportunityService/findOpportunityResponse")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
    partName="parameters", name="findOpportunityResponse")
  public com.oracle.ptsdemo.oscproxyclient.types.FindOpportunityResponse findOpportunity(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
      partName="parameters", name="findOpportunity")
    com.oracle.ptsdemo.oscproxyclient.types.FindOpportunity parameters)
    throws com.oracle.ptsdemo.oscproxyclient.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/findOpportunityAsync")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/findOpportunityAsync")
  @Oneway
  public void findOpportunityAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
      partName="parameters", name="findOpportunityAsync")
    com.oracle.ptsdemo.oscproxyclient.types.FindOpportunityAsync parameters);

  @WebMethod(action="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/isSalesAccountUsedInOpportunity")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/isSalesAccountUsedInOpportunity", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/OpportunityService/isSalesAccountUsedInOpportunity/Fault/ServiceException",
          className=com.oracle.ptsdemo.oscproxyclient.ServiceException.class) },
    output="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/OpportunityService/isSalesAccountUsedInOpportunityResponse")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
    partName="parameters", name="isSalesAccountUsedInOpportunityResponse")
  public com.oracle.ptsdemo.oscproxyclient.types.IsSalesAccountUsedInOpportunityResponse isSalesAccountUsedInOpportunity(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
      partName="parameters", name="isSalesAccountUsedInOpportunity")
    com.oracle.ptsdemo.oscproxyclient.types.IsSalesAccountUsedInOpportunity parameters)
    throws com.oracle.ptsdemo.oscproxyclient.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/isSalesAccountUsedInOpportunityAsync")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/isSalesAccountUsedInOpportunityAsync")
  @Oneway
  public void isSalesAccountUsedInOpportunityAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
      partName="parameters", name="isSalesAccountUsedInOpportunityAsync")
    com.oracle.ptsdemo.oscproxyclient.types.IsSalesAccountUsedInOpportunityAsync parameters);

  @WebMethod(action="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/checkConstraint")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/checkConstraint", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/OpportunityService/checkConstraint/Fault/ServiceException",
          className=com.oracle.ptsdemo.oscproxyclient.ServiceException.class) },
    output="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/OpportunityService/checkConstraintResponse")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
    partName="parameters", name="checkConstraintResponse")
  public com.oracle.ptsdemo.oscproxyclient.types.CheckConstraintResponse checkConstraint(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
      partName="parameters", name="checkConstraint")
    com.oracle.ptsdemo.oscproxyclient.types.CheckConstraint parameters)
    throws com.oracle.ptsdemo.oscproxyclient.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/checkConstraintAsync")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/checkConstraintAsync")
  @Oneway
  public void checkConstraintAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
      partName="parameters", name="checkConstraintAsync")
    com.oracle.ptsdemo.oscproxyclient.types.CheckConstraintAsync parameters);

  @WebMethod(action="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/getDfltObjAttrHints")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/getDfltObjAttrHints", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/OpportunityService/getDfltObjAttrHints/Fault/ServiceException",
          className=com.oracle.ptsdemo.oscproxyclient.ServiceException.class) },
    output="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/OpportunityService/getDfltObjAttrHintsResponse")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
    partName="parameters", name="getDfltObjAttrHintsResponse")
  public com.oracle.ptsdemo.oscproxyclient.types.GetDfltObjAttrHintsResponse getDfltObjAttrHints(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
      partName="parameters", name="getDfltObjAttrHints")
    com.oracle.ptsdemo.oscproxyclient.types.GetDfltObjAttrHints parameters)
    throws com.oracle.ptsdemo.oscproxyclient.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/getServiceLastUpdateTime")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/getServiceLastUpdateTime", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/OpportunityService/getServiceLastUpdateTime/Fault/ServiceException",
          className=com.oracle.ptsdemo.oscproxyclient.ServiceException.class) },
    output="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/OpportunityService/getServiceLastUpdateTimeResponse")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
    partName="parameters", name="getServiceLastUpdateTimeResponse")
  public com.oracle.ptsdemo.oscproxyclient.types.GetServiceLastUpdateTimeResponse getServiceLastUpdateTime(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
      partName="parameters", name="getServiceLastUpdateTime")
    com.oracle.ptsdemo.oscproxyclient.types.GetServiceLastUpdateTime parameters)
    throws com.oracle.ptsdemo.oscproxyclient.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/getEntityList")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/getEntityList", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/OpportunityService/getEntityList/Fault/ServiceException",
          className=com.oracle.ptsdemo.oscproxyclient.ServiceException.class) },
    output="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/OpportunityService/getEntityListResponse")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
    partName="parameters", name="getEntityListResponse")
  public com.oracle.ptsdemo.oscproxyclient.types.GetEntityListResponse getEntityList(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
      partName="parameters", name="getEntityList")
    com.oracle.ptsdemo.oscproxyclient.types.GetEntityList parameters)
    throws com.oracle.ptsdemo.oscproxyclient.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/getEntityListAsync")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/getEntityListAsync")
  @Oneway
  public void getEntityListAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
      partName="parameters", name="getEntityListAsync")
    com.oracle.ptsdemo.oscproxyclient.types.GetEntityListAsync parameters);

  @WebMethod(action="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/getDfltObjAttrHintsAsync")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/getDfltObjAttrHintsAsync")
  @Oneway
  public void getDfltObjAttrHintsAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
      partName="parameters", name="getDfltObjAttrHintsAsync")
    com.oracle.ptsdemo.oscproxyclient.types.GetDfltObjAttrHintsAsync parameters);

  @WebMethod(action="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/getServiceLastUpdateTimeAsync")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/getServiceLastUpdateTimeAsync")
  @Oneway
  public void getServiceLastUpdateTimeAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/",
      partName="parameters", name="getServiceLastUpdateTimeAsync")
    com.oracle.ptsdemo.oscproxyclient.types.GetServiceLastUpdateTimeAsync parameters);
}
