package oracle.demo.pts.fusionproxy.userservice;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebServiceClient(wsdlLocation="https://dummy.oracleads.com:443/hcmPeopleRolesV2/UserDetailsService?WSDL",
  targetNamespace="http://xmlns.oracle.com/apps/hcm/people/roles/userDetailsServiceV2/",
  name="UserDetailsService")
public class UserDetailsService_Service
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  { logger = Logger.getLogger("oracle.demo.pts.fusionproxy.userservice.UserDetailsService_Service");
    /* try
    {
     
      URL baseUrl = UserDetailsService_Service.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            UserDetailsService_Service.class.getResource("https://dummy.oracleads.com:443/hcmPeopleRolesV2/UserDetailsService?WSDL");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "https://dummy.oracleads.com:443/hcmPeopleRolesV2/UserDetailsService?WSDL");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, "https://dummy.oracleads.com:443/hcmPeopleRolesV2/UserDetailsService?WSDL");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using https://dummy.oracleads.com:443/hcmPeopleRolesV2/UserDetailsService?WSDL",
          e);
    } */
  }

  public UserDetailsService_Service()
  {
    super(wsdlLocationURL,
          new QName("http://xmlns.oracle.com/apps/hcm/people/roles/userDetailsServiceV2/",
                    "UserDetailsService"));
  }

  public UserDetailsService_Service(URL wsdlLocation, QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="UserDetailsServiceSoapHttpPort")
  public oracle.demo.pts.fusionproxy.userservice.UserDetailsService getUserDetailsServiceSoapHttpPort()
  {
    return (oracle.demo.pts.fusionproxy.userservice.UserDetailsService) super.getPort(new QName("http://xmlns.oracle.com/apps/hcm/people/roles/userDetailsServiceV2/",
                                                                                                "UserDetailsServiceSoapHttpPort"),
                                                                                      oracle.demo.pts.fusionproxy.userservice.UserDetailsService.class);
  }

  @WebEndpoint(name="UserDetailsServiceSoapHttpPort")
  public oracle.demo.pts.fusionproxy.userservice.UserDetailsService getUserDetailsServiceSoapHttpPort(WebServiceFeature... features)
  {
    return (oracle.demo.pts.fusionproxy.userservice.UserDetailsService) super.getPort(new QName("http://xmlns.oracle.com/apps/hcm/people/roles/userDetailsServiceV2/",
                                                                                                "UserDetailsServiceSoapHttpPort"),
                                                                                      oracle.demo.pts.fusionproxy.userservice.UserDetailsService.class,
                                                                                      features);
  }
}
