<wsdl:definitions
     name="PersonService"
     targetNamespace="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:errors="http://xmlns.oracle.com/adf/svc/errors/"
     xmlns:orafault="http://xmlns.oracle.com/oracleas/schema/oracle-fault-11_0"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/"
     xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
     xmlns:types="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/types/"
    >
    <wsdl:documentation xmlns:oer="http://xmlns.oracle.com/oer">
        <name>Trading Community Person Information</name>
        <description>An individual who either directly enters into a business
            relationship or represents an organization in a business
            relationship. For example, John Doe, Mary Doe who works at Oracle.</description>
        <docCategories>
            <category>Integration</category>
        </docCategories>
        <oer:lifecycle>Active</oer:lifecycle>
        <oer:compatibility>Supported - Backward Compatibility Assured</oer:compatibility>
        <oer:category name="lba">
            <value>CdmTop-Customer Data Management</value>
            <value>CdmTop-Customer Data Management : FoundationTop-Foundation</value>
            <value>CdmTop-Customer Data Management : FoundationTop-Foundation :
                FoundationParties-Parties</value>
        </oer:category>
        <oer:operation name="getPerson">
            <description>Get operation for Trading Community Person Details</description>
            <oer:parameters>
                <oer:parameter name="partyId" description="Party identifier"/>
                <oer:return description="Trading Community Person Details that matches the inbound key attributes."/>
            </oer:parameters>
        </oer:operation>
        <oer:operation name="createPerson">
            <description>Create operation for Trading Community Person Details</description>
            <oer:parameters>
                <oer:parameter name="personParty" description="Trading Community Person Details to be created"/>
                <oer:return description="Result of the operation includes the successfully created Trading Community Person Details and/or a list of warnings or informational messages."/>
            </oer:parameters>
        </oer:operation>
        <oer:operation name="updatePerson">
            <description>Update operation for Trading Community Person Details</description>
            <oer:parameters>
                <oer:parameter name="personParty" description="Trading Community Person Details to be updated"/>
                <oer:return description="Result of the operation includes the successfully updated Trading Community Person Details and/or a list of warnings or informational messages."/>
            </oer:parameters>
        </oer:operation>
        <oer:operation name="mergePerson">
            <description>Merge operation for Trading Community Person Details. It will
                perform an update if the object exists, or an insert if the
                object doesn&apos;t already exist.</description>
            <oer:parameters>
                <oer:parameter name="personParty" description="Trading Community Person Details to be merged"/>
                <oer:return description="Result of the operation includes the successfully merged Trading Community Person Details and/or a list of warnings or informational messages."/>
            </oer:parameters>
        </oer:operation>
        <oer:operation name="getPersonByOriginalSystemReference">
            <description>Get operation for Trading Community Person filtered by Source
                System Reference</description>
            <oer:parameters>
                <oer:parameter name="findCriteria" description="The criteria used to limit your query result, such as the filter (where clause), the fetch size, etc."/>
                <oer:parameter name="bindOrigSystem" description="Unique Original System Code"/>
                <oer:parameter name="bindOrigSystemReference" description="Unique Original System Reference Identifier"/>
                <oer:parameter name="findControl" description="Find Control. Not currently used."/>
                <oer:return description="Trading Community Person Details that matches the inbound party usage code."/>
            </oer:parameters>
        </oer:operation>
        <oer:operation name="getPersonsFilteredByPartyUsageCode">
            <description>Get operation for Trading Community Person filtered by Party
                Usage</description>
            <oer:parameters>
                <oer:parameter name="findCriteria" description="The criteria used to limit your query result, such as the filter (where clause), the fetch size, etc."/>
                <oer:parameter name="bindPartyUsageCode" description="Party Usage Code used to filter Persons"/>
                <oer:parameter name="bindEffectiveDate" description="Effective date used to filter the party usages associated with Person"/>
                <oer:parameter name="findControl" description="Find Control. Not currently used."/>
                <oer:return description="Trading Community Person Details that matches the inbound party usage code."/>
            </oer:parameters>
        </oer:operation>
        <oer:operation name="getPersonsFilteredByPartyUsageFilterRuleCode">
            <description>Get operation for Trading Community Person filtered by Party
                Usage Filter Rule</description>
            <oer:parameters>
                <oer:parameter name="findCriteria" description="The criteria used to limit your query result, such as the filter (where clause), the fetch size, etc."/>
                <oer:parameter name="bindPartyUsageFrCode" description="Party Usage filter rule used to filter Person"/>
                <oer:parameter name="bindEffectiveDate" description="Effective date used to filter the party usages associated with Person"/>
                <oer:parameter name="findControl" description="Find Control. Not currently used."/>
                <oer:return description="Trading Community Person Details that matches the inbound party usage filter rule code."/>
            </oer:parameters>
        </oer:operation>
        <oer:operation name="deletePerson">
            <description>Delete operation for Trading Community Person Details</description>
            <oer:parameters>
                <oer:parameter name="personParty" description="Trading Community Person Details to be deleted"/>
                <oer:return description="A list of warnings or informational messages encountered when deleting the object."/>
            </oer:parameters>
        </oer:operation>
        <oer:operation name="processCSPerson">
            <description>An operation to apply the changes back to the data source for
                Trading Community Person Details</description>
            <oer:parameters>
                <oer:parameter name="processData" description="The object that is used to represent the changes that have been made."/>
                <oer:parameter name="processControl" description="Control your bulk upload behavior, such as whether the valid data will be committed if there are other invalid data in the same batch, and whether the outbound will contain the key attributes only or the full object."/>
                <oer:return description="Result of the operation including a list of created/updated data objects, and all warning and informational messages."/>
            </oer:parameters>
        </oer:operation>
        <oer:operation name="findPerson">
            <description>Find operation for Trading Community Person Details</description>
            <oer:parameters>
                <oer:parameter name="findCriteria" description="The criteria used to limit your query result, such as the filter (where clause), the fetch size, etc."/>
                <oer:parameter name="findControl" description="Find Control. Not currently used."/>
                <oer:return description="Result of the operation including a list of Trading Community Person Details that satisfy the inbound criteria and any warnings or informational messages encountered during the invocation."/>
            </oer:parameters>
        </oer:operation>
        <oer:operation name="processPerson">
            <description>Bulk load operation for Trading Community Person Details</description>
            <oer:parameters>
                <oer:parameter name="changeOperation" description="Indicates what action shall be performed, such as Create, Update, Merge, or Delete"/>
                <oer:parameter name="personParty" description="A list of Trading Community Person Details to be processed"/>
                <oer:parameter name="processControl" description="Control your bulk upload behavior, such as whether the valid data will be committed if there are other invalid data in the same batch, and whether the outbound will contain the key attributes only or the full object."/>
                <oer:return description="Result of the operation including a list of Trading Community Person Details that are successfully processed and any warnings or informational messages encountered during the invocation."/>
            </oer:parameters>
        </oer:operation>
        <oer:operation name="getPersonProfile">
            <description>Get operation for Trading Community Person Profile. You can
                query the person profile with PartyId using this operation.</description>
            <oer:parameters>
                <oer:parameter name="PartyId" description="PartyId for the person party."/>
                <oer:return description="Trading Community Person Profile that matches the inbound key attributes."/>
            </oer:parameters>
        </oer:operation>
        <oer:operation name="updatePersonProfile">
            <description>Update operation for Trading Community Person Profile. You can
                update the person profile with PartyId using this operation.</description>
            <oer:parameters>
                <oer:parameter name="personDVO" description="Trading Community Person Profile to be updated"/>
                <oer:return description="Result of the operation includes the successfully updated Trading Community Person Profile and/or a list of warnings or informational messages."/>
            </oer:parameters>
        </oer:operation>
        <oer:operation name="mergePersonProfile">
            <description>Update operation for Trading Community Person Profile. You can
                update the person profile with PartyId using this operation.</description>
            <oer:parameters>
                <oer:parameter name="personDVO" description="Trading Community Person Profile to be merged"/>
                <oer:return description="Result of the operation includes the successfully merged Trading Community Person Profile and/or a list of warnings or informational messages."/>
            </oer:parameters>
        </oer:operation>
        <oer:operation name="findPersonProfile">
            <description>Find operation for Trading Community Person Profile</description>
            <oer:parameters>
                <oer:parameter name="findCriteria" description="The criteria used to limit your query result, such as the filter (where clause), the fetch size, etc."/>
                <oer:parameter name="findControl" description="Find Control. Not currently used."/>
                <oer:return description="Result of the operation including a list of Trading Community Person Profile that satisfy the inbound criteria and any warnings or informational messages encountered during the invocation."/>
            </oer:parameters>
        </oer:operation>
    </wsdl:documentation>
    <plnk:partnerLinkType name="PersonService">
        <plnk:role name="PersonServiceProvider">
            <plnk:portType name="tns:PersonService"/>
        </plnk:role>
        <plnk:role name="PersonServiceRequestor">
            <plnk:portType name="tns:PersonServiceResponse"/>
        </plnk:role>
    </plnk:partnerLinkType>
    <wsp:Policy xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
         wsu:Id="PersonServiceResponse_Fault_Policy" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy"/>
    <wsp:Policy xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
         wsu:Id="PersonServiceResponse_Input_Policy" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy">
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
            <sp:Body/>
            <sp:Header Namespace="http://www.w3.org/2005/08/addressing"/>
            <sp:Header Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing"/>
            <sp:Header Name="fmw-context" Namespace="http://xmlns.oracle.com/fmw/context/1.0"/>
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
            <sp:Body/>
            <sp:Header Name="fmw-context" Namespace="http://xmlns.oracle.com/fmw/context/1.0"/>
        </sp:EncryptedParts>
    </wsp:Policy>
    <wsp:Policy xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
         wsu:Id="PersonServiceResponse_Output_Policy" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy">
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
            <sp:Body/>
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
            <sp:Body/>
        </sp:EncryptedParts>
    </wsp:Policy>
    <wsp:Policy xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
         wsu:Id="PersonServiceSoapHttpPort_Fault_Policy" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy">
        <wsp:ExactlyOne>
            <wsp:All/>
            <wsp:All/>
        </wsp:ExactlyOne>
    </wsp:Policy>
    <wsp:Policy xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
         wsu:Id="PersonServiceSoapHttpPort_Input_Policy" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy">
        <wsp:ExactlyOne>
            <wsp:All>
                <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
                    <sp:Body/>
                    <sp:Header Namespace="http://www.w3.org/2005/08/addressing"/>
                    <sp:Header Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing"/>
                    <sp:Header Name="fmw-context" Namespace="http://xmlns.oracle.com/fmw/context/1.0"/>
                </sp:SignedParts>
                <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
                    <sp:Body/>
                    <sp:Header Name="fmw-context" Namespace="http://xmlns.oracle.com/fmw/context/1.0"/>
                </sp:EncryptedParts>
            </wsp:All>
            <wsp:All>
                <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
                    <sp:Body/>
                    <sp:Header Namespace="http://www.w3.org/2005/08/addressing"/>
                    <sp:Header Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing"/>
                    <sp:Header Name="fmw-context" Namespace="http://xmlns.oracle.com/fmw/context/1.0"/>
                    <sp:Header Name="SignatureConfirmation" Namespace="http://docs.oasis-open.org/wss/oasis-wss-wssecurity-secext-1.1.xsd"/>
                </sp:SignedParts>
                <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
                    <sp:Body/>
                    <sp:Header Name="fmw-context" Namespace="http://xmlns.oracle.com/fmw/context/1.0"/>
                </sp:EncryptedParts>
            </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>
    <wsp:Policy xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
         wsu:Id="PersonServiceSoapHttpPort_Output_Policy" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy">
        <wsp:ExactlyOne>
            <wsp:All>
                <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
                    <sp:Body/>
                </sp:SignedParts>
                <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
                    <sp:Body/>
                </sp:EncryptedParts>
            </wsp:All>
            <wsp:All>
                <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
                    <sp:Body/>
                </sp:SignedParts>
                <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
                    <sp:Body/>
                </sp:EncryptedParts>
            </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>
    <wsp:Policy xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
         wsu:Id="wsaddr_policy" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy">
        <wsaw:UsingAddressing xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl"/>
    </wsp:Policy>
    <wsp:Policy xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
         wsu:Id="wss11_saml_or_username_token_with_message_protection_service_policy">
        <wsp:ExactlyOne>
            <wsp:All>
                <sp:SymmetricBinding xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
                    <wsp:Policy>
                        <sp:ProtectionToken>
                            <wsp:Policy>
                                <sp:X509Token sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/Never">
                                    <wsp:Policy>
                                        <sp:RequireThumbprintReference/>
                                        <sp:WssX509V3Token11/>
                                    </wsp:Policy>
                                </sp:X509Token>
                            </wsp:Policy>
                        </sp:ProtectionToken>
                        <sp:AlgorithmSuite>
                            <wsp:Policy>
                                <sp:Basic128/>
                            </wsp:Policy>
                        </sp:AlgorithmSuite>
                        <sp:Layout>
                            <wsp:Policy>
                                <sp:Lax/>
                            </wsp:Policy>
                        </sp:Layout>
                        <sp:IncludeTimestamp/>
                        <sp:ProtectTokens/>
                        <sp:OnlySignEntireHeadersAndBody/>
                    </wsp:Policy>
                </sp:SymmetricBinding>
                <sp:SignedSupportingTokens xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
                    <wsp:Policy>
                        <sp:SamlToken sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/AlwaysToRecipient">
                            <wsp:Policy>
                                <sp:WssSamlV11Token11/>
                            </wsp:Policy>
                        </sp:SamlToken>
                    </wsp:Policy>
                </sp:SignedSupportingTokens>
                <sp:EndorsingSupportingTokens xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
                    <wsp:Policy>
                        <sp:X509Token sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/AlwaysToRecipient">
                            <wsp:Policy>
                                <sp:WssX509V3Token11/>
                            </wsp:Policy>
                        </sp:X509Token>
                    </wsp:Policy>
                </sp:EndorsingSupportingTokens>
                <sp:Wss11 xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
                    <wsp:Policy>
                        <sp:RequireSignatureConfirmation/>
                        <sp:MustSupportRefEncryptedKey/>
                    </wsp:Policy>
                </sp:Wss11>
            </wsp:All>
            <wsp:All>
                <sp:SymmetricBinding xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
                    <wsp:Policy>
                        <sp:ProtectionToken>
                            <wsp:Policy>
                                <sp:X509Token sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/Never">
                                    <wsp:Policy>
                                        <sp:RequireThumbprintReference/>
                                        <sp:WssX509V3Token11/>
                                    </wsp:Policy>
                                </sp:X509Token>
                            </wsp:Policy>
                        </sp:ProtectionToken>
                        <sp:AlgorithmSuite>
                            <wsp:Policy>
                                <sp:Basic128/>
                            </wsp:Policy>
                        </sp:AlgorithmSuite>
                        <sp:Layout>
                            <wsp:Policy>
                                <sp:Lax/>
                            </wsp:Policy>
                        </sp:Layout>
                        <sp:IncludeTimestamp/>
                        <sp:OnlySignEntireHeadersAndBody/>
                    </wsp:Policy>
                </sp:SymmetricBinding>
                <sp:SignedSupportingTokens xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
                    <wsp:Policy>
                        <sp:UsernameToken sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/AlwaysToRecipient">
                            <wsp:Policy>
                                <sp:WssUsernameToken10/>
                            </wsp:Policy>
                        </sp:UsernameToken>
                    </wsp:Policy>
                </sp:SignedSupportingTokens>
                <sp:Wss11 xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
                    <wsp:Policy>
                        <sp:RequireSignatureConfirmation/>
                        <sp:MustSupportRefEncryptedKey/>
                    </wsp:Policy>
                </sp:Wss11>
            </wsp:All>
            <wsp:All>
                <sp:TransportBinding xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
                    <wsp:Policy>
                        <sp:TransportToken>
                            <wsp:Policy>
                                <sp:HttpsToken RequireClientCertificate="false">
                                    <wsp:Policy/>
                                </sp:HttpsToken>
                            </wsp:Policy>
                        </sp:TransportToken>
                        <sp:Layout>
                            <wsp:Policy>
                                <sp:Lax/>
                            </wsp:Policy>
                        </sp:Layout>
                        <sp:IncludeTimestamp/>
                    </wsp:Policy>
                </sp:TransportBinding>
                <sp:SupportingTokens xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
                    <wsp:Policy>
                        <sp:SamlToken sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/AlwaysToRecipient">
                            <wsp:Policy>
                                <sp:WssSamlV11Token10/>
                            </wsp:Policy>
                        </sp:SamlToken>
                    </wsp:Policy>
                </sp:SupportingTokens>
            </wsp:All>
            <wsp:All>
                <sp:TransportBinding xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
                    <wsp:Policy>
                        <sp:TransportToken>
                            <wsp:Policy>
                                <sp:HttpsToken RequireClientCertificate="false">
                                    <wsp:Policy/>
                                </sp:HttpsToken>
                            </wsp:Policy>
                        </sp:TransportToken>
                        <sp:Layout>
                            <wsp:Policy>
                                <sp:Lax/>
                            </wsp:Policy>
                        </sp:Layout>
                        <sp:IncludeTimestamp/>
                    </wsp:Policy>
                </sp:TransportBinding>
                <sp:SupportingTokens xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
                    <wsp:Policy>
                        <sp:UsernameToken sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/AlwaysToRecipient">
                            <wsp:Policy>
                                <sp:WssUsernameToken10/>
                            </wsp:Policy>
                        </sp:UsernameToken>
                    </wsp:Policy>
                </sp:SupportingTokens>
            </wsp:All>
            <wsp:All>
                <sp:TransportBinding xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
                    <wsp:Policy>
                        <sp:TransportToken>
                            <wsp:Policy>
                                <sp:HttpsToken RequireClientCertificate="false">
                                    <wsp:Policy/>
                                </sp:HttpsToken>
                            </wsp:Policy>
                        </sp:TransportToken>
                        <sp:Layout>
                            <wsp:Policy>
                                <sp:Lax/>
                            </wsp:Policy>
                        </sp:Layout>
                    </wsp:Policy>
                </sp:TransportBinding>
            </wsp:All>
            <wsp:All/>
        </wsp:ExactlyOne>
    </wsp:Policy>
    <wsp:Policy xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
         wsu:Id="wss11_saml_token_with_message_protection_client_policy">
        <sp:SymmetricBinding xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
            <wsp:Policy>
                <sp:ProtectionToken>
                    <wsp:Policy>
                        <sp:X509Token sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/Never">
                            <wsp:Policy>
                                <sp:RequireThumbprintReference/>
                                <sp:WssX509V3Token11/>
                            </wsp:Policy>
                        </sp:X509Token>
                    </wsp:Policy>
                </sp:ProtectionToken>
                <sp:AlgorithmSuite>
                    <wsp:Policy>
                        <sp:Basic128/>
                    </wsp:Policy>
                </sp:AlgorithmSuite>
                <sp:Layout>
                    <wsp:Policy>
                        <sp:Lax/>
                    </wsp:Policy>
                </sp:Layout>
                <sp:IncludeTimestamp/>
                <sp:ProtectTokens/>
                <sp:OnlySignEntireHeadersAndBody/>
            </wsp:Policy>
        </sp:SymmetricBinding>
        <sp:SignedSupportingTokens xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
            <wsp:Policy>
                <sp:SamlToken sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/AlwaysToRecipient">
                    <wsp:Policy>
                        <sp:WssSamlV11Token11/>
                    </wsp:Policy>
                </sp:SamlToken>
            </wsp:Policy>
        </sp:SignedSupportingTokens>
        <sp:EndorsingSupportingTokens xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
            <wsp:Policy>
                <sp:X509Token sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/AlwaysToRecipient">
                    <wsp:Policy>
                        <sp:WssX509V3Token11/>
                    </wsp:Policy>
                </sp:X509Token>
            </wsp:Policy>
        </sp:EndorsingSupportingTokens>
        <sp:Wss11 xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
            <wsp:Policy>
                <sp:RequireSignatureConfirmation/>
                <sp:MustSupportRefEncryptedKey/>
            </wsp:Policy>
        </sp:Wss11>
    </wsp:Policy>
    <wsdl:import namespace="http://xmlns.oracle.com/adf/svc/errors/" location="ServiceException.wsdl"/>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/oracleas/schema/oracle-fault-11_0" schemaLocation="oracle_webservices_async_fault_11_0.xsd"/>
            <import namespace="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/types/"
                 schemaLocation="PersonService.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="PersonService_onFault">
        <wsdl:part name="parameters" element="orafault:Fault"/>
    </wsdl:message>
    <wsdl:message name="PersonService_getPersonByOriginalSystemReferenceAsyncResponse">
        <wsdl:part name="parameters" element="types:getPersonByOriginalSystemReferenceAsyncResponse"/>
    </wsdl:message>
    <wsdl:message name="PersonService_mergePersonAsyncResponse">
        <wsdl:part name="parameters" element="types:mergePersonAsyncResponse"/>
    </wsdl:message>
    <wsdl:message name="PersonService_deletePersonAsyncResponse">
        <wsdl:part name="parameters" element="types:deletePersonAsyncResponse"/>
    </wsdl:message>
    <wsdl:message name="PersonService_processCSPersonAsyncResponse">
        <wsdl:part name="parameters" element="types:processCSPersonAsyncResponse"/>
    </wsdl:message>
    <wsdl:message name="PersonService_getPersonsFilteredByPartyUsageCodeAsyncResponse">
        <wsdl:part name="parameters" element="types:getPersonsFilteredByPartyUsageCodeAsyncResponse"/>
    </wsdl:message>
    <wsdl:message name="PersonService_createPersonAsyncResponse">
        <wsdl:part name="parameters" element="types:createPersonAsyncResponse"/>
    </wsdl:message>
    <wsdl:message name="PersonService_updatePersonAsyncResponse">
        <wsdl:part name="parameters" element="types:updatePersonAsyncResponse"/>
    </wsdl:message>
    <wsdl:message name="PersonService_getPersonAsyncResponse">
        <wsdl:part name="parameters" element="types:getPersonAsyncResponse"/>
    </wsdl:message>
    <wsdl:message name="PersonService_getPersonsFilteredByPartyUsageFilterRuleCodeAsyncResponse">
        <wsdl:part name="parameters" element="types:getPersonsFilteredByPartyUsageFilterRuleCodeAsyncResponse"/>
    </wsdl:message>
    <wsdl:message name="PersonService_processPersonAsyncResponse">
        <wsdl:part name="parameters" element="types:processPersonAsyncResponse"/>
    </wsdl:message>
    <wsdl:message name="PersonService_findPersonAsyncResponse">
        <wsdl:part name="parameters" element="types:findPersonAsyncResponse"/>
    </wsdl:message>
    <wsdl:message name="PersonService_getPersonProfileAsyncResponse">
        <wsdl:part name="parameters" element="types:getPersonProfileAsyncResponse"/>
    </wsdl:message>
    <wsdl:message name="PersonService_updatePersonProfileAsyncResponse">
        <wsdl:part name="parameters" element="types:updatePersonProfileAsyncResponse"/>
    </wsdl:message>
    <wsdl:message name="PersonService_mergePersonProfileAsyncResponse">
        <wsdl:part name="parameters" element="types:mergePersonProfileAsyncResponse"/>
    </wsdl:message>
    <wsdl:message name="PersonService_findPersonProfileAsyncResponse">
        <wsdl:part name="parameters" element="types:findPersonProfileAsyncResponse"/>
    </wsdl:message>
    <wsdl:message name="PersonService_getPerson">
        <wsdl:part name="parameters" element="types:getPerson"/>
    </wsdl:message>
    <wsdl:message name="PersonService_getPersonResponse">
        <wsdl:part name="parameters" element="types:getPersonResponse"/>
    </wsdl:message>
    <wsdl:message name="PersonService_createPerson">
        <wsdl:part name="parameters" element="types:createPerson"/>
    </wsdl:message>
    <wsdl:message name="PersonService_createPersonResponse">
        <wsdl:part name="parameters" element="types:createPersonResponse"/>
    </wsdl:message>
    <wsdl:message name="PersonService_updatePerson">
        <wsdl:part name="parameters" element="types:updatePerson"/>
    </wsdl:message>
    <wsdl:message name="PersonService_updatePersonResponse">
        <wsdl:part name="parameters" element="types:updatePersonResponse"/>
    </wsdl:message>
    <wsdl:message name="PersonService_mergePerson">
        <wsdl:part name="parameters" element="types:mergePerson"/>
    </wsdl:message>
    <wsdl:message name="PersonService_mergePersonResponse">
        <wsdl:part name="parameters" element="types:mergePersonResponse"/>
    </wsdl:message>
    <wsdl:message name="PersonService_getPersonByOriginalSystemReference">
        <wsdl:part name="parameters" element="types:getPersonByOriginalSystemReference"/>
    </wsdl:message>
    <wsdl:message name="PersonService_getPersonByOriginalSystemReferenceResponse">
        <wsdl:part name="parameters" element="types:getPersonByOriginalSystemReferenceResponse"/>
    </wsdl:message>
    <wsdl:message name="PersonService_getPersonsFilteredByPartyUsageCode">
        <wsdl:part name="parameters" element="types:getPersonsFilteredByPartyUsageCode"/>
    </wsdl:message>
    <wsdl:message name="PersonService_getPersonsFilteredByPartyUsageCodeResponse">
        <wsdl:part name="parameters" element="types:getPersonsFilteredByPartyUsageCodeResponse"/>
    </wsdl:message>
    <wsdl:message name="PersonService_getPersonsFilteredByPartyUsageFilterRuleCode">
        <wsdl:part name="parameters" element="types:getPersonsFilteredByPartyUsageFilterRuleCode"/>
    </wsdl:message>
    <wsdl:message name="PersonService_getPersonsFilteredByPartyUsageFilterRuleCodeResponse">
        <wsdl:part name="parameters" element="types:getPersonsFilteredByPartyUsageFilterRuleCodeResponse"/>
    </wsdl:message>
    <wsdl:message name="PersonService_deletePerson">
        <wsdl:part name="parameters" element="types:deletePerson"/>
    </wsdl:message>
    <wsdl:message name="PersonService_deletePersonResponse">
        <wsdl:part name="parameters" element="types:deletePersonResponse"/>
    </wsdl:message>
    <wsdl:message name="PersonService_processCSPerson">
        <wsdl:part name="parameters" element="types:processCSPerson"/>
    </wsdl:message>
    <wsdl:message name="PersonService_processCSPersonResponse">
        <wsdl:part name="parameters" element="types:processCSPersonResponse"/>
    </wsdl:message>
    <wsdl:message name="PersonService_getPersonByOriginalSystemReferenceAsync">
        <wsdl:part name="parameters" element="types:getPersonByOriginalSystemReferenceAsync"/>
    </wsdl:message>
    <wsdl:message name="PersonService_mergePersonAsync">
        <wsdl:part name="parameters" element="types:mergePersonAsync"/>
    </wsdl:message>
    <wsdl:message name="PersonService_deletePersonAsync">
        <wsdl:part name="parameters" element="types:deletePersonAsync"/>
    </wsdl:message>
    <wsdl:message name="PersonService_processCSPersonAsync">
        <wsdl:part name="parameters" element="types:processCSPersonAsync"/>
    </wsdl:message>
    <wsdl:message name="PersonService_getPersonsFilteredByPartyUsageCodeAsync">
        <wsdl:part name="parameters" element="types:getPersonsFilteredByPartyUsageCodeAsync"/>
    </wsdl:message>
    <wsdl:message name="PersonService_createPersonAsync">
        <wsdl:part name="parameters" element="types:createPersonAsync"/>
    </wsdl:message>
    <wsdl:message name="PersonService_updatePersonAsync">
        <wsdl:part name="parameters" element="types:updatePersonAsync"/>
    </wsdl:message>
    <wsdl:message name="PersonService_getPersonAsync">
        <wsdl:part name="parameters" element="types:getPersonAsync"/>
    </wsdl:message>
    <wsdl:message name="PersonService_getPersonsFilteredByPartyUsageFilterRuleCodeAsync">
        <wsdl:part name="parameters" element="types:getPersonsFilteredByPartyUsageFilterRuleCodeAsync"/>
    </wsdl:message>
    <wsdl:message name="PersonService_findPerson">
        <wsdl:part name="parameters" element="types:findPerson"/>
    </wsdl:message>
    <wsdl:message name="PersonService_findPersonResponse">
        <wsdl:part name="parameters" element="types:findPersonResponse"/>
    </wsdl:message>
    <wsdl:message name="PersonService_processPerson">
        <wsdl:part name="parameters" element="types:processPerson"/>
    </wsdl:message>
    <wsdl:message name="PersonService_processPersonResponse">
        <wsdl:part name="parameters" element="types:processPersonResponse"/>
    </wsdl:message>
    <wsdl:message name="PersonService_processPersonAsync">
        <wsdl:part name="parameters" element="types:processPersonAsync"/>
    </wsdl:message>
    <wsdl:message name="PersonService_findPersonAsync">
        <wsdl:part name="parameters" element="types:findPersonAsync"/>
    </wsdl:message>
    <wsdl:message name="PersonService_getPersonProfile">
        <wsdl:part name="parameters" element="types:getPersonProfile"/>
    </wsdl:message>
    <wsdl:message name="PersonService_getPersonProfileResponse">
        <wsdl:part name="parameters" element="types:getPersonProfileResponse"/>
    </wsdl:message>
    <wsdl:message name="PersonService_getPersonProfileAsync">
        <wsdl:part name="parameters" element="types:getPersonProfileAsync"/>
    </wsdl:message>
    <wsdl:message name="PersonService_updatePersonProfile">
        <wsdl:part name="parameters" element="types:updatePersonProfile"/>
    </wsdl:message>
    <wsdl:message name="PersonService_updatePersonProfileResponse">
        <wsdl:part name="parameters" element="types:updatePersonProfileResponse"/>
    </wsdl:message>
    <wsdl:message name="PersonService_mergePersonProfile">
        <wsdl:part name="parameters" element="types:mergePersonProfile"/>
    </wsdl:message>
    <wsdl:message name="PersonService_mergePersonProfileResponse">
        <wsdl:part name="parameters" element="types:mergePersonProfileResponse"/>
    </wsdl:message>
    <wsdl:message name="PersonService_updatePersonProfileAsync">
        <wsdl:part name="parameters" element="types:updatePersonProfileAsync"/>
    </wsdl:message>
    <wsdl:message name="PersonService_mergePersonProfileAsync">
        <wsdl:part name="parameters" element="types:mergePersonProfileAsync"/>
    </wsdl:message>
    <wsdl:message name="PersonService_findPersonProfile">
        <wsdl:part name="parameters" element="types:findPersonProfile"/>
    </wsdl:message>
    <wsdl:message name="PersonService_findPersonProfileResponse">
        <wsdl:part name="parameters" element="types:findPersonProfileResponse"/>
    </wsdl:message>
    <wsdl:message name="PersonService_findPersonProfileAsync">
        <wsdl:part name="parameters" element="types:findPersonProfileAsync"/>
    </wsdl:message>
    <wsdl:portType name="PersonServiceResponse">
        <wsdl:operation name="onFault">
            <wsdl:input message="tns:PersonService_onFault" xmlns:ns1="http://www.w3.org/2006/05/addressing/wsdl"
                 ns1:Action="http://xmlns.oracle.com/oracleas/schema/oracle-fault-11_0/Fault"/>
        </wsdl:operation>
        <wsdl:operation name="getPersonByOriginalSystemReferenceAsyncResponse">
            <wsdl:input message="tns:PersonService_getPersonByOriginalSystemReferenceAsyncResponse"
                 xmlns:ns1="http://www.w3.org/2006/05/addressing/wsdl" ns1:Action="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/getPersonByOriginalSystemReferenceAsyncResponse"/>
        </wsdl:operation>
        <wsdl:operation name="mergePersonAsyncResponse">
            <wsdl:input message="tns:PersonService_mergePersonAsyncResponse" xmlns:ns1="http://www.w3.org/2006/05/addressing/wsdl"
                 ns1:Action="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/mergePersonAsyncResponse"/>
        </wsdl:operation>
        <wsdl:operation name="deletePersonAsyncResponse">
            <wsdl:input message="tns:PersonService_deletePersonAsyncResponse" xmlns:ns1="http://www.w3.org/2006/05/addressing/wsdl"
                 ns1:Action="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/deletePersonAsyncResponse"/>
        </wsdl:operation>
        <wsdl:operation name="processCSPersonAsyncResponse">
            <wsdl:input message="tns:PersonService_processCSPersonAsyncResponse" xmlns:ns1="http://www.w3.org/2006/05/addressing/wsdl"
                 ns1:Action="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/processCSPersonAsyncResponse"/>
        </wsdl:operation>
        <wsdl:operation name="getPersonsFilteredByPartyUsageCodeAsyncResponse">
            <wsdl:input message="tns:PersonService_getPersonsFilteredByPartyUsageCodeAsyncResponse"
                 xmlns:ns1="http://www.w3.org/2006/05/addressing/wsdl" ns1:Action="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/getPersonsFilteredByPartyUsageCodeAsyncResponse"/>
        </wsdl:operation>
        <wsdl:operation name="createPersonAsyncResponse">
            <wsdl:input message="tns:PersonService_createPersonAsyncResponse" xmlns:ns1="http://www.w3.org/2006/05/addressing/wsdl"
                 ns1:Action="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/createPersonAsyncResponse"/>
        </wsdl:operation>
        <wsdl:operation name="updatePersonAsyncResponse">
            <wsdl:input message="tns:PersonService_updatePersonAsyncResponse" xmlns:ns1="http://www.w3.org/2006/05/addressing/wsdl"
                 ns1:Action="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/updatePersonAsyncResponse"/>
        </wsdl:operation>
        <wsdl:operation name="getPersonAsyncResponse">
            <wsdl:input message="tns:PersonService_getPersonAsyncResponse" xmlns:ns1="http://www.w3.org/2006/05/addressing/wsdl"
                 ns1:Action="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/getPersonAsyncResponse"/>
        </wsdl:operation>
        <wsdl:operation name="getPersonsFilteredByPartyUsageFilterRuleCodeAsyncResponse">
            <wsdl:input message="tns:PersonService_getPersonsFilteredByPartyUsageFilterRuleCodeAsyncResponse"
                 xmlns:ns1="http://www.w3.org/2006/05/addressing/wsdl" ns1:Action="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/getPersonsFilteredByPartyUsageFilterRuleCodeAsyncResponse"/>
        </wsdl:operation>
        <wsdl:operation name="processPersonAsyncResponse">
            <wsdl:input message="tns:PersonService_processPersonAsyncResponse" xmlns:ns1="http://www.w3.org/2006/05/addressing/wsdl"
                 ns1:Action="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/processPersonAsyncResponse"/>
        </wsdl:operation>
        <wsdl:operation name="findPersonAsyncResponse">
            <wsdl:input message="tns:PersonService_findPersonAsyncResponse" xmlns:ns1="http://www.w3.org/2006/05/addressing/wsdl"
                 ns1:Action="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/findPersonAsyncResponse"/>
        </wsdl:operation>
        <wsdl:operation name="getPersonProfileAsyncResponse">
            <wsdl:input message="tns:PersonService_getPersonProfileAsyncResponse" xmlns:ns1="http://www.w3.org/2006/05/addressing/wsdl"
                 ns1:Action="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/getPersonProfileAsyncResponse"/>
        </wsdl:operation>
        <wsdl:operation name="updatePersonProfileAsyncResponse">
            <wsdl:input message="tns:PersonService_updatePersonProfileAsyncResponse" xmlns:ns1="http://www.w3.org/2006/05/addressing/wsdl"
                 ns1:Action="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/updatePersonProfileAsyncResponse"/>
        </wsdl:operation>
        <wsdl:operation name="mergePersonProfileAsyncResponse">
            <wsdl:input message="tns:PersonService_mergePersonProfileAsyncResponse" xmlns:ns1="http://www.w3.org/2006/05/addressing/wsdl"
                 ns1:Action="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/mergePersonProfileAsyncResponse"/>
        </wsdl:operation>
        <wsdl:operation name="findPersonProfileAsyncResponse">
            <wsdl:input message="tns:PersonService_findPersonProfileAsyncResponse" xmlns:ns1="http://www.w3.org/2006/05/addressing/wsdl"
                 ns1:Action="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/findPersonProfileAsyncResponse"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:portType name="PersonService">
        <wsdl:documentation>
            <ViewInstance xmlns="http://xmlns.oracle.com/adf/svc/metadata/" Name="PersonDVO" xmlns:ns0="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/"
                 SDOName="ns0:PersonProfile" UpdateOpName="updatePersonProfile" MergeOpName="mergePersonProfile"
                 FindOpName="findPersonProfile"/>
            <ViewInstance xmlns="http://xmlns.oracle.com/adf/svc/metadata/" Name="PersonParty" xmlns:ns0="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/"
                 SDOName="ns0:Person" CreateOpName="createPerson" UpdateOpName="updatePerson"
                 DeleteOpName="deletePerson" MergeOpName="mergePerson" GetOpName="getPerson"
                 FindOpName="findPerson" ProcessOpName="processPerson" ProcessCSOpName="processCSPerson"/>
        </wsdl:documentation>
        <wsdl:operation name="getPerson">
            <wsdl:input message="tns:PersonService_getPerson"/>
            <wsdl:output message="tns:PersonService_getPersonResponse"/>
            <wsdl:fault name="ServiceException" message="errors:ServiceException"/>
        </wsdl:operation>
        <wsdl:operation name="createPerson">
            <wsdl:input message="tns:PersonService_createPerson"/>
            <wsdl:output message="tns:PersonService_createPersonResponse"/>
            <wsdl:fault name="ServiceException" message="errors:ServiceException"/>
        </wsdl:operation>
        <wsdl:operation name="updatePerson">
            <wsdl:input message="tns:PersonService_updatePerson"/>
            <wsdl:output message="tns:PersonService_updatePersonResponse"/>
            <wsdl:fault name="ServiceException" message="errors:ServiceException"/>
        </wsdl:operation>
        <wsdl:operation name="mergePerson">
            <wsdl:input message="tns:PersonService_mergePerson"/>
            <wsdl:output message="tns:PersonService_mergePersonResponse"/>
            <wsdl:fault name="ServiceException" message="errors:ServiceException"/>
        </wsdl:operation>
        <wsdl:operation name="getPersonByOriginalSystemReference">
            <wsdl:input message="tns:PersonService_getPersonByOriginalSystemReference"/>
            <wsdl:output message="tns:PersonService_getPersonByOriginalSystemReferenceResponse"/>
            <wsdl:fault name="ServiceException" message="errors:ServiceException"/>
        </wsdl:operation>
        <wsdl:operation name="getPersonsFilteredByPartyUsageCode">
            <wsdl:input message="tns:PersonService_getPersonsFilteredByPartyUsageCode"/>
            <wsdl:output message="tns:PersonService_getPersonsFilteredByPartyUsageCodeResponse"/>
            <wsdl:fault name="ServiceException" message="errors:ServiceException"/>
        </wsdl:operation>
        <wsdl:operation name="getPersonsFilteredByPartyUsageFilterRuleCode">
            <wsdl:input message="tns:PersonService_getPersonsFilteredByPartyUsageFilterRuleCode"/>
            <wsdl:output message="tns:PersonService_getPersonsFilteredByPartyUsageFilterRuleCodeResponse"/>
            <wsdl:fault name="ServiceException" message="errors:ServiceException"/>
        </wsdl:operation>
        <wsdl:operation name="deletePerson">
            <wsdl:input message="tns:PersonService_deletePerson"/>
            <wsdl:output message="tns:PersonService_deletePersonResponse"/>
            <wsdl:fault name="ServiceException" message="errors:ServiceException"/>
        </wsdl:operation>
        <wsdl:operation name="processCSPerson">
            <wsdl:input message="tns:PersonService_processCSPerson"/>
            <wsdl:output message="tns:PersonService_processCSPersonResponse"/>
            <wsdl:fault name="ServiceException" message="errors:ServiceException"/>
        </wsdl:operation>
        <wsdl:operation name="getPersonByOriginalSystemReferenceAsync">
            <wsdl:input message="tns:PersonService_getPersonByOriginalSystemReferenceAsync" xmlns:ns1="http://www.w3.org/2006/05/addressing/wsdl"
                 ns1:Action="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/getPersonByOriginalSystemReferenceAsync"/>
        </wsdl:operation>
        <wsdl:operation name="mergePersonAsync">
            <wsdl:input message="tns:PersonService_mergePersonAsync" xmlns:ns1="http://www.w3.org/2006/05/addressing/wsdl"
                 ns1:Action="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/mergePersonAsync"/>
        </wsdl:operation>
        <wsdl:operation name="deletePersonAsync">
            <wsdl:input message="tns:PersonService_deletePersonAsync" xmlns:ns1="http://www.w3.org/2006/05/addressing/wsdl"
                 ns1:Action="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/deletePersonAsync"/>
        </wsdl:operation>
        <wsdl:operation name="processCSPersonAsync">
            <wsdl:input message="tns:PersonService_processCSPersonAsync" xmlns:ns1="http://www.w3.org/2006/05/addressing/wsdl"
                 ns1:Action="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/processCSPersonAsync"/>
        </wsdl:operation>
        <wsdl:operation name="getPersonsFilteredByPartyUsageCodeAsync">
            <wsdl:input message="tns:PersonService_getPersonsFilteredByPartyUsageCodeAsync" xmlns:ns1="http://www.w3.org/2006/05/addressing/wsdl"
                 ns1:Action="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/getPersonsFilteredByPartyUsageCodeAsync"/>
        </wsdl:operation>
        <wsdl:operation name="createPersonAsync">
            <wsdl:input message="tns:PersonService_createPersonAsync" xmlns:ns1="http://www.w3.org/2006/05/addressing/wsdl"
                 ns1:Action="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/createPersonAsync"/>
        </wsdl:operation>
        <wsdl:operation name="updatePersonAsync">
            <wsdl:input message="tns:PersonService_updatePersonAsync" xmlns:ns1="http://www.w3.org/2006/05/addressing/wsdl"
                 ns1:Action="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/updatePersonAsync"/>
        </wsdl:operation>
        <wsdl:operation name="getPersonAsync">
            <wsdl:input message="tns:PersonService_getPersonAsync" xmlns:ns1="http://www.w3.org/2006/05/addressing/wsdl"
                 ns1:Action="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/getPersonAsync"/>
        </wsdl:operation>
        <wsdl:operation name="getPersonsFilteredByPartyUsageFilterRuleCodeAsync">
            <wsdl:input message="tns:PersonService_getPersonsFilteredByPartyUsageFilterRuleCodeAsync"
                 xmlns:ns1="http://www.w3.org/2006/05/addressing/wsdl" ns1:Action="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/getPersonsFilteredByPartyUsageFilterRuleCodeAsync"/>
        </wsdl:operation>
        <wsdl:operation name="findPerson">
            <wsdl:input message="tns:PersonService_findPerson"/>
            <wsdl:output message="tns:PersonService_findPersonResponse"/>
            <wsdl:fault name="ServiceException" message="errors:ServiceException"/>
        </wsdl:operation>
        <wsdl:operation name="processPerson">
            <wsdl:input message="tns:PersonService_processPerson"/>
            <wsdl:output message="tns:PersonService_processPersonResponse"/>
            <wsdl:fault name="ServiceException" message="errors:ServiceException"/>
        </wsdl:operation>
        <wsdl:operation name="processPersonAsync">
            <wsdl:input message="tns:PersonService_processPersonAsync" xmlns:ns1="http://www.w3.org/2006/05/addressing/wsdl"
                 ns1:Action="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/processPersonAsync"/>
        </wsdl:operation>
        <wsdl:operation name="findPersonAsync">
            <wsdl:input message="tns:PersonService_findPersonAsync" xmlns:ns1="http://www.w3.org/2006/05/addressing/wsdl"
                 ns1:Action="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/findPersonAsync"/>
        </wsdl:operation>
        <wsdl:operation name="getPersonProfile">
            <wsdl:input message="tns:PersonService_getPersonProfile"/>
            <wsdl:output message="tns:PersonService_getPersonProfileResponse"/>
            <wsdl:fault name="ServiceException" message="errors:ServiceException"/>
        </wsdl:operation>
        <wsdl:operation name="getPersonProfileAsync">
            <wsdl:input message="tns:PersonService_getPersonProfileAsync" xmlns:ns1="http://www.w3.org/2006/05/addressing/wsdl"
                 ns1:Action="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/getPersonProfileAsync"/>
        </wsdl:operation>
        <wsdl:operation name="updatePersonProfile">
            <wsdl:input message="tns:PersonService_updatePersonProfile"/>
            <wsdl:output message="tns:PersonService_updatePersonProfileResponse"/>
            <wsdl:fault name="ServiceException" message="errors:ServiceException"/>
        </wsdl:operation>
        <wsdl:operation name="mergePersonProfile">
            <wsdl:input message="tns:PersonService_mergePersonProfile"/>
            <wsdl:output message="tns:PersonService_mergePersonProfileResponse"/>
            <wsdl:fault name="ServiceException" message="errors:ServiceException"/>
        </wsdl:operation>
        <wsdl:operation name="updatePersonProfileAsync">
            <wsdl:input message="tns:PersonService_updatePersonProfileAsync" xmlns:ns1="http://www.w3.org/2006/05/addressing/wsdl"
                 ns1:Action="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/updatePersonProfileAsync"/>
        </wsdl:operation>
        <wsdl:operation name="mergePersonProfileAsync">
            <wsdl:input message="tns:PersonService_mergePersonProfileAsync" xmlns:ns1="http://www.w3.org/2006/05/addressing/wsdl"
                 ns1:Action="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/mergePersonProfileAsync"/>
        </wsdl:operation>
        <wsdl:operation name="findPersonProfile">
            <wsdl:input message="tns:PersonService_findPersonProfile"/>
            <wsdl:output message="tns:PersonService_findPersonProfileResponse"/>
            <wsdl:fault name="ServiceException" message="errors:ServiceException"/>
        </wsdl:operation>
        <wsdl:operation name="findPersonProfileAsync">
            <wsdl:input message="tns:PersonService_findPersonProfileAsync" xmlns:ns1="http://www.w3.org/2006/05/addressing/wsdl"
                 ns1:Action="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/findPersonProfileAsync"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="PersonServiceResponseBinding" type="tns:PersonServiceResponse">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#wss11_saml_token_with_message_protection_client_policy"
             wsdl:required="false"/>
        <wsdl:operation name="onFault">
            <soap:operation soapAction="http://xmlns.oracle.com/oracleas/schema/oracle-fault-11_0/Fault"/>
            <wsdl:input>
                <soap:body use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceResponse_Input_Policy"
                     wsdl:required="false"/>
            </wsdl:input>
        </wsdl:operation>
        <wsdl:operation name="getPersonByOriginalSystemReferenceAsyncResponse">
            <soap:operation soapAction="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/getPersonByOriginalSystemReferenceAsyncResponse"/>
            <wsdl:input>
                <soap:body use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceResponse_Input_Policy"
                     wsdl:required="false"/>
            </wsdl:input>
        </wsdl:operation>
        <wsdl:operation name="mergePersonAsyncResponse">
            <soap:operation soapAction="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/mergePersonAsyncResponse"/>
            <wsdl:input>
                <soap:body use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceResponse_Input_Policy"
                     wsdl:required="false"/>
            </wsdl:input>
        </wsdl:operation>
        <wsdl:operation name="deletePersonAsyncResponse">
            <soap:operation soapAction="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/deletePersonAsyncResponse"/>
            <wsdl:input>
                <soap:body use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceResponse_Input_Policy"
                     wsdl:required="false"/>
            </wsdl:input>
        </wsdl:operation>
        <wsdl:operation name="processCSPersonAsyncResponse">
            <soap:operation soapAction="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/processCSPersonAsyncResponse"/>
            <wsdl:input>
                <soap:body use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceResponse_Input_Policy"
                     wsdl:required="false"/>
            </wsdl:input>
        </wsdl:operation>
        <wsdl:operation name="getPersonsFilteredByPartyUsageCodeAsyncResponse">
            <soap:operation soapAction="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/getPersonsFilteredByPartyUsageCodeAsyncResponse"/>
            <wsdl:input>
                <soap:body use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceResponse_Input_Policy"
                     wsdl:required="false"/>
            </wsdl:input>
        </wsdl:operation>
        <wsdl:operation name="createPersonAsyncResponse">
            <soap:operation soapAction="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/createPersonAsyncResponse"/>
            <wsdl:input>
                <soap:body use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceResponse_Input_Policy"
                     wsdl:required="false"/>
            </wsdl:input>
        </wsdl:operation>
        <wsdl:operation name="updatePersonAsyncResponse">
            <soap:operation soapAction="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/updatePersonAsyncResponse"/>
            <wsdl:input>
                <soap:body use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceResponse_Input_Policy"
                     wsdl:required="false"/>
            </wsdl:input>
        </wsdl:operation>
        <wsdl:operation name="getPersonAsyncResponse">
            <soap:operation soapAction="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/getPersonAsyncResponse"/>
            <wsdl:input>
                <soap:body use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceResponse_Input_Policy"
                     wsdl:required="false"/>
            </wsdl:input>
        </wsdl:operation>
        <wsdl:operation name="getPersonsFilteredByPartyUsageFilterRuleCodeAsyncResponse">
            <soap:operation soapAction="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/getPersonsFilteredByPartyUsageFilterRuleCodeAsyncResponse"/>
            <wsdl:input>
                <soap:body use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceResponse_Input_Policy"
                     wsdl:required="false"/>
            </wsdl:input>
        </wsdl:operation>
        <wsdl:operation name="processPersonAsyncResponse">
            <soap:operation soapAction="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/processPersonAsyncResponse"/>
            <wsdl:input>
                <soap:body use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceResponse_Input_Policy"
                     wsdl:required="false"/>
            </wsdl:input>
        </wsdl:operation>
        <wsdl:operation name="findPersonAsyncResponse">
            <soap:operation soapAction="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/findPersonAsyncResponse"/>
            <wsdl:input>
                <soap:body use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceResponse_Input_Policy"
                     wsdl:required="false"/>
            </wsdl:input>
        </wsdl:operation>
        <wsdl:operation name="getPersonProfileAsyncResponse">
            <soap:operation soapAction="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/getPersonProfileAsyncResponse"/>
            <wsdl:input>
                <soap:body use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceResponse_Input_Policy"
                     wsdl:required="false"/>
            </wsdl:input>
        </wsdl:operation>
        <wsdl:operation name="updatePersonProfileAsyncResponse">
            <soap:operation soapAction="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/updatePersonProfileAsyncResponse"/>
            <wsdl:input>
                <soap:body use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceResponse_Input_Policy"
                     wsdl:required="false"/>
            </wsdl:input>
        </wsdl:operation>
        <wsdl:operation name="mergePersonProfileAsyncResponse">
            <soap:operation soapAction="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/mergePersonProfileAsyncResponse"/>
            <wsdl:input>
                <soap:body use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceResponse_Input_Policy"
                     wsdl:required="false"/>
            </wsdl:input>
        </wsdl:operation>
        <wsdl:operation name="findPersonProfileAsyncResponse">
            <soap:operation soapAction="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/findPersonProfileAsyncResponse"/>
            <wsdl:input>
                <soap:body use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceResponse_Input_Policy"
                     wsdl:required="false"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:binding name="PersonServiceSoapHttp" type="tns:PersonService">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#wss11_saml_or_username_token_with_message_protection_service_policy"
             wsdl:required="false"/>
        <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#wsaddr_policy"
             wsdl:required="false"/>
        <wsdl:operation name="getPerson">
            <soap:operation soapAction="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/getPerson"/>
            <wsdl:input>
                <soap:body use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceSoapHttpPort_Input_Policy"
                     wsdl:required="false"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceSoapHttpPort_Output_Policy"
                     wsdl:required="false"/>
            </wsdl:output>
            <wsdl:fault name="ServiceException">
                <soap:fault name="ServiceException" use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceSoapHttpPort_Fault_Policy"
                     wsdl:required="false"/>
            </wsdl:fault>
        </wsdl:operation>
        <wsdl:operation name="createPerson">
            <soap:operation soapAction="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/createPerson"/>
            <wsdl:input>
                <soap:body use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceSoapHttpPort_Input_Policy"
                     wsdl:required="false"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceSoapHttpPort_Output_Policy"
                     wsdl:required="false"/>
            </wsdl:output>
            <wsdl:fault name="ServiceException">
                <soap:fault name="ServiceException" use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceSoapHttpPort_Fault_Policy"
                     wsdl:required="false"/>
            </wsdl:fault>
        </wsdl:operation>
        <wsdl:operation name="updatePerson">
            <soap:operation soapAction="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/updatePerson"/>
            <wsdl:input>
                <soap:body use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceSoapHttpPort_Input_Policy"
                     wsdl:required="false"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceSoapHttpPort_Output_Policy"
                     wsdl:required="false"/>
            </wsdl:output>
            <wsdl:fault name="ServiceException">
                <soap:fault name="ServiceException" use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceSoapHttpPort_Fault_Policy"
                     wsdl:required="false"/>
            </wsdl:fault>
        </wsdl:operation>
        <wsdl:operation name="mergePerson">
            <soap:operation soapAction="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/mergePerson"/>
            <wsdl:input>
                <soap:body use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceSoapHttpPort_Input_Policy"
                     wsdl:required="false"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceSoapHttpPort_Output_Policy"
                     wsdl:required="false"/>
            </wsdl:output>
            <wsdl:fault name="ServiceException">
                <soap:fault name="ServiceException" use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceSoapHttpPort_Fault_Policy"
                     wsdl:required="false"/>
            </wsdl:fault>
        </wsdl:operation>
        <wsdl:operation name="getPersonByOriginalSystemReference">
            <soap:operation soapAction="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/getPersonByOriginalSystemReference"/>
            <wsdl:input>
                <soap:body use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceSoapHttpPort_Input_Policy"
                     wsdl:required="false"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceSoapHttpPort_Output_Policy"
                     wsdl:required="false"/>
            </wsdl:output>
            <wsdl:fault name="ServiceException">
                <soap:fault name="ServiceException" use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceSoapHttpPort_Fault_Policy"
                     wsdl:required="false"/>
            </wsdl:fault>
        </wsdl:operation>
        <wsdl:operation name="getPersonsFilteredByPartyUsageCode">
            <soap:operation soapAction="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/getPersonsFilteredByPartyUsageCode"/>
            <wsdl:input>
                <soap:body use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceSoapHttpPort_Input_Policy"
                     wsdl:required="false"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceSoapHttpPort_Output_Policy"
                     wsdl:required="false"/>
            </wsdl:output>
            <wsdl:fault name="ServiceException">
                <soap:fault name="ServiceException" use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceSoapHttpPort_Fault_Policy"
                     wsdl:required="false"/>
            </wsdl:fault>
        </wsdl:operation>
        <wsdl:operation name="getPersonsFilteredByPartyUsageFilterRuleCode">
            <soap:operation soapAction="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/getPersonsFilteredByPartyUsageFilterRuleCode"/>
            <wsdl:input>
                <soap:body use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceSoapHttpPort_Input_Policy"
                     wsdl:required="false"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceSoapHttpPort_Output_Policy"
                     wsdl:required="false"/>
            </wsdl:output>
            <wsdl:fault name="ServiceException">
                <soap:fault name="ServiceException" use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceSoapHttpPort_Fault_Policy"
                     wsdl:required="false"/>
            </wsdl:fault>
        </wsdl:operation>
        <wsdl:operation name="deletePerson">
            <soap:operation soapAction="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/deletePerson"/>
            <wsdl:input>
                <soap:body use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceSoapHttpPort_Input_Policy"
                     wsdl:required="false"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceSoapHttpPort_Output_Policy"
                     wsdl:required="false"/>
            </wsdl:output>
            <wsdl:fault name="ServiceException">
                <soap:fault name="ServiceException" use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceSoapHttpPort_Fault_Policy"
                     wsdl:required="false"/>
            </wsdl:fault>
        </wsdl:operation>
        <wsdl:operation name="processCSPerson">
            <soap:operation soapAction="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/processCSPerson"/>
            <wsdl:input>
                <soap:body use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceSoapHttpPort_Input_Policy"
                     wsdl:required="false"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceSoapHttpPort_Output_Policy"
                     wsdl:required="false"/>
            </wsdl:output>
            <wsdl:fault name="ServiceException">
                <soap:fault name="ServiceException" use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceSoapHttpPort_Fault_Policy"
                     wsdl:required="false"/>
            </wsdl:fault>
        </wsdl:operation>
        <wsdl:operation name="getPersonByOriginalSystemReferenceAsync">
            <soap:operation soapAction="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/getPersonByOriginalSystemReferenceAsync"/>
            <wsdl:input>
                <soap:body use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceSoapHttpPort_Input_Policy"
                     wsdl:required="false"/>
            </wsdl:input>
        </wsdl:operation>
        <wsdl:operation name="mergePersonAsync">
            <soap:operation soapAction="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/mergePersonAsync"/>
            <wsdl:input>
                <soap:body use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceSoapHttpPort_Input_Policy"
                     wsdl:required="false"/>
            </wsdl:input>
        </wsdl:operation>
        <wsdl:operation name="deletePersonAsync">
            <soap:operation soapAction="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/deletePersonAsync"/>
            <wsdl:input>
                <soap:body use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceSoapHttpPort_Input_Policy"
                     wsdl:required="false"/>
            </wsdl:input>
        </wsdl:operation>
        <wsdl:operation name="processCSPersonAsync">
            <soap:operation soapAction="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/processCSPersonAsync"/>
            <wsdl:input>
                <soap:body use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceSoapHttpPort_Input_Policy"
                     wsdl:required="false"/>
            </wsdl:input>
        </wsdl:operation>
        <wsdl:operation name="getPersonsFilteredByPartyUsageCodeAsync">
            <soap:operation soapAction="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/getPersonsFilteredByPartyUsageCodeAsync"/>
            <wsdl:input>
                <soap:body use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceSoapHttpPort_Input_Policy"
                     wsdl:required="false"/>
            </wsdl:input>
        </wsdl:operation>
        <wsdl:operation name="createPersonAsync">
            <soap:operation soapAction="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/createPersonAsync"/>
            <wsdl:input>
                <soap:body use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceSoapHttpPort_Input_Policy"
                     wsdl:required="false"/>
            </wsdl:input>
        </wsdl:operation>
        <wsdl:operation name="updatePersonAsync">
            <soap:operation soapAction="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/updatePersonAsync"/>
            <wsdl:input>
                <soap:body use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceSoapHttpPort_Input_Policy"
                     wsdl:required="false"/>
            </wsdl:input>
        </wsdl:operation>
        <wsdl:operation name="getPersonAsync">
            <soap:operation soapAction="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/getPersonAsync"/>
            <wsdl:input>
                <soap:body use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceSoapHttpPort_Input_Policy"
                     wsdl:required="false"/>
            </wsdl:input>
        </wsdl:operation>
        <wsdl:operation name="getPersonsFilteredByPartyUsageFilterRuleCodeAsync">
            <soap:operation soapAction="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/getPersonsFilteredByPartyUsageFilterRuleCodeAsync"/>
            <wsdl:input>
                <soap:body use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceSoapHttpPort_Input_Policy"
                     wsdl:required="false"/>
            </wsdl:input>
        </wsdl:operation>
        <wsdl:operation name="findPerson">
            <soap:operation soapAction="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/findPerson"/>
            <wsdl:input>
                <soap:body use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceSoapHttpPort_Input_Policy"
                     wsdl:required="false"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceSoapHttpPort_Output_Policy"
                     wsdl:required="false"/>
            </wsdl:output>
            <wsdl:fault name="ServiceException">
                <soap:fault name="ServiceException" use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceSoapHttpPort_Fault_Policy"
                     wsdl:required="false"/>
            </wsdl:fault>
        </wsdl:operation>
        <wsdl:operation name="processPerson">
            <soap:operation soapAction="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/processPerson"/>
            <wsdl:input>
                <soap:body use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceSoapHttpPort_Input_Policy"
                     wsdl:required="false"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceSoapHttpPort_Output_Policy"
                     wsdl:required="false"/>
            </wsdl:output>
            <wsdl:fault name="ServiceException">
                <soap:fault name="ServiceException" use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceSoapHttpPort_Fault_Policy"
                     wsdl:required="false"/>
            </wsdl:fault>
        </wsdl:operation>
        <wsdl:operation name="processPersonAsync">
            <soap:operation soapAction="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/processPersonAsync"/>
            <wsdl:input>
                <soap:body use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceSoapHttpPort_Input_Policy"
                     wsdl:required="false"/>
            </wsdl:input>
        </wsdl:operation>
        <wsdl:operation name="findPersonAsync">
            <soap:operation soapAction="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/findPersonAsync"/>
            <wsdl:input>
                <soap:body use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceSoapHttpPort_Input_Policy"
                     wsdl:required="false"/>
            </wsdl:input>
        </wsdl:operation>
        <wsdl:operation name="getPersonProfile">
            <soap:operation soapAction="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/getPersonProfile"/>
            <wsdl:input>
                <soap:body use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceSoapHttpPort_Input_Policy"
                     wsdl:required="false"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceSoapHttpPort_Output_Policy"
                     wsdl:required="false"/>
            </wsdl:output>
            <wsdl:fault name="ServiceException">
                <soap:fault name="ServiceException" use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceSoapHttpPort_Fault_Policy"
                     wsdl:required="false"/>
            </wsdl:fault>
        </wsdl:operation>
        <wsdl:operation name="getPersonProfileAsync">
            <soap:operation soapAction="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/getPersonProfileAsync"/>
            <wsdl:input>
                <soap:body use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceSoapHttpPort_Input_Policy"
                     wsdl:required="false"/>
            </wsdl:input>
        </wsdl:operation>
        <wsdl:operation name="updatePersonProfile">
            <soap:operation soapAction="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/updatePersonProfile"/>
            <wsdl:input>
                <soap:body use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceSoapHttpPort_Input_Policy"
                     wsdl:required="false"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceSoapHttpPort_Output_Policy"
                     wsdl:required="false"/>
            </wsdl:output>
            <wsdl:fault name="ServiceException">
                <soap:fault name="ServiceException" use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceSoapHttpPort_Fault_Policy"
                     wsdl:required="false"/>
            </wsdl:fault>
        </wsdl:operation>
        <wsdl:operation name="mergePersonProfile">
            <soap:operation soapAction="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/mergePersonProfile"/>
            <wsdl:input>
                <soap:body use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceSoapHttpPort_Input_Policy"
                     wsdl:required="false"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceSoapHttpPort_Output_Policy"
                     wsdl:required="false"/>
            </wsdl:output>
            <wsdl:fault name="ServiceException">
                <soap:fault name="ServiceException" use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceSoapHttpPort_Fault_Policy"
                     wsdl:required="false"/>
            </wsdl:fault>
        </wsdl:operation>
        <wsdl:operation name="updatePersonProfileAsync">
            <soap:operation soapAction="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/updatePersonProfileAsync"/>
            <wsdl:input>
                <soap:body use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceSoapHttpPort_Input_Policy"
                     wsdl:required="false"/>
            </wsdl:input>
        </wsdl:operation>
        <wsdl:operation name="mergePersonProfileAsync">
            <soap:operation soapAction="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/mergePersonProfileAsync"/>
            <wsdl:input>
                <soap:body use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceSoapHttpPort_Input_Policy"
                     wsdl:required="false"/>
            </wsdl:input>
        </wsdl:operation>
        <wsdl:operation name="findPersonProfile">
            <soap:operation soapAction="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/findPersonProfile"/>
            <wsdl:input>
                <soap:body use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceSoapHttpPort_Input_Policy"
                     wsdl:required="false"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceSoapHttpPort_Output_Policy"
                     wsdl:required="false"/>
            </wsdl:output>
            <wsdl:fault name="ServiceException">
                <soap:fault name="ServiceException" use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceSoapHttpPort_Fault_Policy"
                     wsdl:required="false"/>
            </wsdl:fault>
        </wsdl:operation>
        <wsdl:operation name="findPersonProfileAsync">
            <soap:operation soapAction="http://xmlns.oracle.com/apps/cdm/foundation/parties/personService/applicationModule/findPersonProfileAsync"/>
            <wsdl:input>
                <soap:body use="literal"/>
                <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#PersonServiceSoapHttpPort_Input_Policy"
                     wsdl:required="false"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="PersonService">
        <wsdl:port name="PersonServiceSoapHttpPort" binding="tns:PersonServiceSoapHttp">
            <soap:address location="https://dummy-crm-crm-ext.oracle.com:443/foundationParties/PersonService"/>
            <wsa:EndpointReference xmlns:wsa="http://www.w3.org/2005/08/addressing">
                <wsa:Address xmlns:wsa="http://www.w3.org/2005/08/addressing">https://dummy-crm-crm-ext.oracle.com:443/foundationParties/PersonService</wsa:Address>
                <wsid:Identity xmlns:wsid="http://schemas.xmlsoap.org/ws/2006/02/addressingidentity">
                    <dsig:KeyInfo xmlns:dsig="http://www.w3.org/2000/09/xmldsig#">
                        <dsig:X509Data>
                            <dsig:X509Certificate>MIICCzCCAXSgAwIBAgIEUgXqFzANBgkqhkiG9w0BAQUFADBKMRMwEQYKCZImiZPyLGQBGRYDY29tMSEwHwYKCZImiZPyLGQBGRYRb3JhY2xlb3V0c291cmNpbmcxEDAOBgNVBAMTB3NlcnZpY2UwHhcNMTMwODEwMDcyMTU5WhcNMTYwODEwMDcyMTU5WjBKMRMwEQYKCZImiZPyLGQBGRYDY29tMSEwHwYKCZImiZPyLGQBGRYRb3JhY2xlb3V0c291cmNpbmcxEDAOBgNVBAMTB3NlcnZpY2UwgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBAIwwJxN+lZcxofSpjLD83O4JqO4XW5MrJD/GyUr4MuEQ/K1xYLr8a3qD+p38ld/Bs1ydFr2toCALmJ/vH8vqrcf3+6WQUQwotOrRbctUirs37rF5EUNJS6mCy2LrJz2OjEIc50TCvz4T3krl8r9/AL9ZV4tfthz350Cgw1aU+V3HAgMBAAEwDQYJKoZIhvcNAQEFBQADgYEAM9f1nGbsHbO8iT5qgQpFvzX5Lreqk1D1fT7mI07LQ4YydjnIjCJQ8QY635iFW1+GrJeFFgae95N8c3chMdpH4EUnxmahfJMnoX0xAkijIXwvui6QVkKY/XcBwpFFoJVxA8gZRTIU7K9C2E7BBFJquANsPvpuPwEdet3qXj2Ai1g=</dsig:X509Certificate>
                            <dsig:X509IssuerSerial>
                                <dsig:X509IssuerName>CN=service, DC=oracleoutsourcing, DC=com</dsig:X509IssuerName>
                                <dsig:X509SerialNumber>1376119319</dsig:X509SerialNumber>
                            </dsig:X509IssuerSerial>
                            <dsig:X509SubjectName>CN=service, DC=oracleoutsourcing, DC=com</dsig:X509SubjectName>
                        </dsig:X509Data>
                    </dsig:KeyInfo>
                </wsid:Identity>
            </wsa:EndpointReference>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
