package com.oracle.ptsdemo.healthcare.wsclient.pharmacy;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebService(wsdlLocation="https://jcs.my-oraclecloudapps.com/Pharmacy/PharmacyWSPort?WSDL",
  targetNamespace="http://pharmacy.webservice.pts.oracle.com/", name="PharmacyWS")
@XmlSeeAlso(
  { com.oracle.ptsdemo.healthcare.wsclient.pharmacy.types.ObjectFactory.class })
public interface PharmacyWS
{
  @WebMethod
  @Action(input="http://pharmacy.webservice.pts.oracle.com/PharmacyWS/createMedicationRequest",
    output="http://pharmacy.webservice.pts.oracle.com/PharmacyWS/createMedicationResponse")
  @ResponseWrapper(localName="createMedicationResponse", targetNamespace="http://pharmacy.webservice.pts.oracle.com/",
    className="com.oracle.ptsdemo.healthcare.wsclient.pharmacy.types.CreateMedicationResponse")
  @RequestWrapper(localName="createMedication", targetNamespace="http://pharmacy.webservice.pts.oracle.com/",
    className="com.oracle.ptsdemo.healthcare.wsclient.pharmacy.types.CreateMedication")
  @WebResult(targetNamespace="")
  public String createMedication(@WebParam(targetNamespace="", name="arg0")
    com.oracle.ptsdemo.healthcare.wsclient.pharmacy.types.Medication arg0);

  @WebMethod
  @Action(input="http://pharmacy.webservice.pts.oracle.com/PharmacyWS/isMedicationReadyToPickupRequest",
    output="http://pharmacy.webservice.pts.oracle.com/PharmacyWS/isMedicationReadyToPickupResponse")
  @ResponseWrapper(localName="isMedicationReadyToPickupResponse",
    targetNamespace="http://pharmacy.webservice.pts.oracle.com/",
    className="com.oracle.ptsdemo.healthcare.wsclient.pharmacy.types.IsMedicationReadyToPickupResponse")
  @RequestWrapper(localName="isMedicationReadyToPickup", targetNamespace="http://pharmacy.webservice.pts.oracle.com/",
    className="com.oracle.ptsdemo.healthcare.wsclient.pharmacy.types.IsMedicationReadyToPickup")
  @WebResult(targetNamespace="")
  public boolean isMedicationReadyToPickup(@WebParam(targetNamespace="",
      name="arg0")
    String arg0);

  @WebMethod
  @Action(input="http://pharmacy.webservice.pts.oracle.com/PharmacyWS/requestOrderStatusRequest",
    output="http://pharmacy.webservice.pts.oracle.com/PharmacyWS/requestOrderStatusResponse")
  @ResponseWrapper(localName="requestOrderStatusResponse",
    targetNamespace="http://pharmacy.webservice.pts.oracle.com/",
    className="com.oracle.ptsdemo.healthcare.wsclient.pharmacy.types.RequestOrderStatusResponse")
  @RequestWrapper(localName="requestOrderStatus", targetNamespace="http://pharmacy.webservice.pts.oracle.com/",
    className="com.oracle.ptsdemo.healthcare.wsclient.pharmacy.types.RequestOrderStatus")
  @WebResult(targetNamespace="")
  public String requestOrderStatus(@WebParam(targetNamespace="", name="arg0")
    String arg0);

  @WebMethod
  @Action(input="http://pharmacy.webservice.pts.oracle.com/PharmacyWS/setMedicationReadyToPickup")
  @RequestWrapper(localName="setMedicationReadyToPickup", targetNamespace="http://pharmacy.webservice.pts.oracle.com/",
    className="com.oracle.ptsdemo.healthcare.wsclient.pharmacy.types.SetMedicationReadyToPickup")
  @Oneway
  public void setMedicationReadyToPickup(@WebParam(targetNamespace="",
      name="arg0")
    String arg0);

  @WebMethod
  @Action(input="http://pharmacy.webservice.pts.oracle.com/PharmacyWS/loadMedicationListFromHealthCare")
  @RequestWrapper(localName="loadMedicationListFromHealthCare",
    targetNamespace="http://pharmacy.webservice.pts.oracle.com/",
    className="com.oracle.ptsdemo.healthcare.wsclient.pharmacy.types.LoadMedicationListFromHealthCare")
  @Oneway
  public void loadMedicationListFromHealthCare();

  @WebMethod
  @Action(input="http://pharmacy.webservice.pts.oracle.com/PharmacyWS/loadMedicationListForHealthCare")
  @RequestWrapper(localName="loadMedicationListForHealthCare",
    targetNamespace="http://pharmacy.webservice.pts.oracle.com/",
    className="com.oracle.ptsdemo.healthcare.wsclient.pharmacy.types.LoadMedicationListForHealthCare")
  @Oneway
  public void loadMedicationListForHealthCare();

  @WebMethod
  @Action(input="http://pharmacy.webservice.pts.oracle.com/PharmacyWS/loadHealthCareProviderList")
  @RequestWrapper(localName="loadHealthCareProviderList", targetNamespace="http://pharmacy.webservice.pts.oracle.com/",
    className="com.oracle.ptsdemo.healthcare.wsclient.pharmacy.types.LoadHealthCareProviderList")
  @Oneway
  public void loadHealthCareProviderList();

  @WebMethod
  @Action(input="http://pharmacy.webservice.pts.oracle.com/PharmacyWS/createPrescription")
  @RequestWrapper(localName="createPrescription", targetNamespace="http://pharmacy.webservice.pts.oracle.com/",
    className="com.oracle.ptsdemo.healthcare.wsclient.pharmacy.types.CreatePrescription")
  @Oneway
  public void createPrescription(@WebParam(targetNamespace="", name="arg0")
    com.oracle.ptsdemo.healthcare.wsclient.pharmacy.types.Prescription arg0);
}
