//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.24 at 02:07:49 PM BST 
//


package com.oracle.xmlns.apps.crmcommon.activities.activitiesservice._transient.types;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.oracle.xmlns.apps.crmcommon.activities.activitiesservice._transient.types package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.oracle.xmlns.apps.crmcommon.activities.activitiesservice._transient.types
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UpdateNotesResponse }
     * 
     */
    public UpdateNotesResponse createUpdateNotesResponse() {
        return new UpdateNotesResponse();
    }

    /**
     * Create an instance of {@link GetActivityContactAsync }
     * 
     */
    public GetActivityContactAsync createGetActivityContactAsync() {
        return new GetActivityContactAsync();
    }

    /**
     * Create an instance of {@link DeleteActivityContactAsync }
     * 
     */
    public DeleteActivityContactAsync createDeleteActivityContactAsync() {
        return new DeleteActivityContactAsync();
    }

    /**
     * Create an instance of {@link CreateActivityAssignee }
     * 
     */
    public CreateActivityAssignee createCreateActivityAssignee() {
        return new CreateActivityAssignee();
    }

    /**
     * Create an instance of {@link CreateActivityContactAsyncResponse }
     * 
     */
    public CreateActivityContactAsyncResponse createCreateActivityContactAsyncResponse() {
        return new CreateActivityContactAsyncResponse();
    }

    /**
     * Create an instance of {@link UpdateActivityCategories }
     * 
     */
    public UpdateActivityCategories createUpdateActivityCategories() {
        return new UpdateActivityCategories();
    }

    /**
     * Create an instance of {@link MergeAppointmentAsyncResponse }
     * 
     */
    public MergeAppointmentAsyncResponse createMergeAppointmentAsyncResponse() {
        return new MergeAppointmentAsyncResponse();
    }

    /**
     * Create an instance of {@link GetActivityCategoriesAsyncResponse }
     * 
     */
    public GetActivityCategoriesAsyncResponse createGetActivityCategoriesAsyncResponse() {
        return new GetActivityCategoriesAsyncResponse();
    }

    /**
     * Create an instance of {@link UpdateActivityCategoriesAsync }
     * 
     */
    public UpdateActivityCategoriesAsync createUpdateActivityCategoriesAsync() {
        return new UpdateActivityCategoriesAsync();
    }

    /**
     * Create an instance of {@link GetAppointmentDeleteExceptionAsyncResponse }
     * 
     */
    public GetAppointmentDeleteExceptionAsyncResponse createGetAppointmentDeleteExceptionAsyncResponse() {
        return new GetAppointmentDeleteExceptionAsyncResponse();
    }

    /**
     * Create an instance of {@link DeleteAttachmentAsyncResponse }
     * 
     */
    public DeleteAttachmentAsyncResponse createDeleteAttachmentAsyncResponse() {
        return new DeleteAttachmentAsyncResponse();
    }

    /**
     * Create an instance of {@link DeleteAppointmentAsyncResponse }
     * 
     */
    public DeleteAppointmentAsyncResponse createDeleteAppointmentAsyncResponse() {
        return new DeleteAppointmentAsyncResponse();
    }

    /**
     * Create an instance of {@link GetAppointmentResponse }
     * 
     */
    public GetAppointmentResponse createGetAppointmentResponse() {
        return new GetAppointmentResponse();
    }

    /**
     * Create an instance of {@link UpdateNotesAsync }
     * 
     */
    public UpdateNotesAsync createUpdateNotesAsync() {
        return new UpdateNotesAsync();
    }

    /**
     * Create an instance of {@link GetAppointmentAsyncResponse }
     * 
     */
    public GetAppointmentAsyncResponse createGetAppointmentAsyncResponse() {
        return new GetAppointmentAsyncResponse();
    }

    /**
     * Create an instance of {@link UpdateActivityAssigneeAsync }
     * 
     */
    public UpdateActivityAssigneeAsync createUpdateActivityAssigneeAsync() {
        return new UpdateActivityAssigneeAsync();
    }

    /**
     * Create an instance of {@link UpdateActivityCategoriesResponse }
     * 
     */
    public UpdateActivityCategoriesResponse createUpdateActivityCategoriesResponse() {
        return new UpdateActivityCategoriesResponse();
    }

    /**
     * Create an instance of {@link FindNotesAsync }
     * 
     */
    public FindNotesAsync createFindNotesAsync() {
        return new FindNotesAsync();
    }

    /**
     * Create an instance of {@link CreateAppointmentAsync }
     * 
     */
    public CreateAppointmentAsync createCreateAppointmentAsync() {
        return new CreateAppointmentAsync();
    }

    /**
     * Create an instance of {@link CreateActivityCategoriesAsync }
     * 
     */
    public CreateActivityCategoriesAsync createCreateActivityCategoriesAsync() {
        return new CreateActivityCategoriesAsync();
    }

    /**
     * Create an instance of {@link FindAppointmentDeleteExceptionAsync }
     * 
     */
    public FindAppointmentDeleteExceptionAsync createFindAppointmentDeleteExceptionAsync() {
        return new FindAppointmentDeleteExceptionAsync();
    }

    /**
     * Create an instance of {@link DeleteActivityCategoriesAsyncResponse }
     * 
     */
    public DeleteActivityCategoriesAsyncResponse createDeleteActivityCategoriesAsyncResponse() {
        return new DeleteActivityCategoriesAsyncResponse();
    }

    /**
     * Create an instance of {@link CreateActivityCategoriesResponse }
     * 
     */
    public CreateActivityCategoriesResponse createCreateActivityCategoriesResponse() {
        return new CreateActivityCategoriesResponse();
    }

    /**
     * Create an instance of {@link CopyAttachmentAsyncResponse }
     * 
     */
    public CopyAttachmentAsyncResponse createCopyAttachmentAsyncResponse() {
        return new CopyAttachmentAsyncResponse();
    }

    /**
     * Create an instance of {@link UpdateAppointmentDeleteExceptionAsync }
     * 
     */
    public UpdateAppointmentDeleteExceptionAsync createUpdateAppointmentDeleteExceptionAsync() {
        return new UpdateAppointmentDeleteExceptionAsync();
    }

    /**
     * Create an instance of {@link GetActivityAssignee }
     * 
     */
    public GetActivityAssignee createGetActivityAssignee() {
        return new GetActivityAssignee();
    }

    /**
     * Create an instance of {@link FindAppointmentDeleteExceptionResponse }
     * 
     */
    public FindAppointmentDeleteExceptionResponse createFindAppointmentDeleteExceptionResponse() {
        return new FindAppointmentDeleteExceptionResponse();
    }

    /**
     * Create an instance of {@link DeleteAppointment }
     * 
     */
    public DeleteAppointment createDeleteAppointment() {
        return new DeleteAppointment();
    }

    /**
     * Create an instance of {@link MergeAppointmentAsync }
     * 
     */
    public MergeAppointmentAsync createMergeAppointmentAsync() {
        return new MergeAppointmentAsync();
    }

    /**
     * Create an instance of {@link MergeAppointmentResponse }
     * 
     */
    public MergeAppointmentResponse createMergeAppointmentResponse() {
        return new MergeAppointmentResponse();
    }

    /**
     * Create an instance of {@link DeleteActivityAssigneeAsyncResponse }
     * 
     */
    public DeleteActivityAssigneeAsyncResponse createDeleteActivityAssigneeAsyncResponse() {
        return new DeleteActivityAssigneeAsyncResponse();
    }

    /**
     * Create an instance of {@link CreateNotesResponse }
     * 
     */
    public CreateNotesResponse createCreateNotesResponse() {
        return new CreateNotesResponse();
    }

    /**
     * Create an instance of {@link FindAppointmentAsync }
     * 
     */
    public FindAppointmentAsync createFindAppointmentAsync() {
        return new FindAppointmentAsync();
    }

    /**
     * Create an instance of {@link FindAppointmentDeleteExceptionAsyncResponse }
     * 
     */
    public FindAppointmentDeleteExceptionAsyncResponse createFindAppointmentDeleteExceptionAsyncResponse() {
        return new FindAppointmentDeleteExceptionAsyncResponse();
    }

    /**
     * Create an instance of {@link CreateActivityContactAsync }
     * 
     */
    public CreateActivityContactAsync createCreateActivityContactAsync() {
        return new CreateActivityContactAsync();
    }

    /**
     * Create an instance of {@link DeleteActivityContactAsyncResponse }
     * 
     */
    public DeleteActivityContactAsyncResponse createDeleteActivityContactAsyncResponse() {
        return new DeleteActivityContactAsyncResponse();
    }

    /**
     * Create an instance of {@link UpdateAppointmentDeleteExceptionResponse }
     * 
     */
    public UpdateAppointmentDeleteExceptionResponse createUpdateAppointmentDeleteExceptionResponse() {
        return new UpdateAppointmentDeleteExceptionResponse();
    }

    /**
     * Create an instance of {@link GetActivityCategoriesAsync }
     * 
     */
    public GetActivityCategoriesAsync createGetActivityCategoriesAsync() {
        return new GetActivityCategoriesAsync();
    }

    /**
     * Create an instance of {@link UpdateNotesAsyncResponse }
     * 
     */
    public UpdateNotesAsyncResponse createUpdateNotesAsyncResponse() {
        return new UpdateNotesAsyncResponse();
    }

    /**
     * Create an instance of {@link GetAppointmentAsync }
     * 
     */
    public GetAppointmentAsync createGetAppointmentAsync() {
        return new GetAppointmentAsync();
    }

    /**
     * Create an instance of {@link DeleteActivityAssigneeResponse }
     * 
     */
    public DeleteActivityAssigneeResponse createDeleteActivityAssigneeResponse() {
        return new DeleteActivityAssigneeResponse();
    }

    /**
     * Create an instance of {@link GetAppointmentDeleteException }
     * 
     */
    public GetAppointmentDeleteException createGetAppointmentDeleteException() {
        return new GetAppointmentDeleteException();
    }

    /**
     * Create an instance of {@link FindAppointmentDeleteException }
     * 
     */
    public FindAppointmentDeleteException createFindAppointmentDeleteException() {
        return new FindAppointmentDeleteException();
    }

    /**
     * Create an instance of {@link DeleteNotes }
     * 
     */
    public DeleteNotes createDeleteNotes() {
        return new DeleteNotes();
    }

    /**
     * Create an instance of {@link CreateActivityContact }
     * 
     */
    public CreateActivityContact createCreateActivityContact() {
        return new CreateActivityContact();
    }

    /**
     * Create an instance of {@link GetActivityCategoriesResponse }
     * 
     */
    public GetActivityCategoriesResponse createGetActivityCategoriesResponse() {
        return new GetActivityCategoriesResponse();
    }

    /**
     * Create an instance of {@link UpdateAppointmentResponse }
     * 
     */
    public UpdateAppointmentResponse createUpdateAppointmentResponse() {
        return new UpdateAppointmentResponse();
    }

    /**
     * Create an instance of {@link CreateAppointmentResponse }
     * 
     */
    public CreateAppointmentResponse createCreateAppointmentResponse() {
        return new CreateAppointmentResponse();
    }

    /**
     * Create an instance of {@link UpdateAppointmentDeleteExceptionAsyncResponse }
     * 
     */
    public UpdateAppointmentDeleteExceptionAsyncResponse createUpdateAppointmentDeleteExceptionAsyncResponse() {
        return new UpdateAppointmentDeleteExceptionAsyncResponse();
    }

    /**
     * Create an instance of {@link GetAttachment }
     * 
     */
    public GetAttachment createGetAttachment() {
        return new GetAttachment();
    }

    /**
     * Create an instance of {@link CreateAppointmentDeleteExceptionResponse }
     * 
     */
    public CreateAppointmentDeleteExceptionResponse createCreateAppointmentDeleteExceptionResponse() {
        return new CreateAppointmentDeleteExceptionResponse();
    }

    /**
     * Create an instance of {@link DeleteNotesResponse }
     * 
     */
    public DeleteNotesResponse createDeleteNotesResponse() {
        return new DeleteNotesResponse();
    }

    /**
     * Create an instance of {@link UpdateAppointmentAsync }
     * 
     */
    public UpdateAppointmentAsync createUpdateAppointmentAsync() {
        return new UpdateAppointmentAsync();
    }

    /**
     * Create an instance of {@link CreateActivityCategories }
     * 
     */
    public CreateActivityCategories createCreateActivityCategories() {
        return new CreateActivityCategories();
    }

    /**
     * Create an instance of {@link FindAppointmentAsyncResponse }
     * 
     */
    public FindAppointmentAsyncResponse createFindAppointmentAsyncResponse() {
        return new FindAppointmentAsyncResponse();
    }

    /**
     * Create an instance of {@link CreateAttachment }
     * 
     */
    public CreateAttachment createCreateAttachment() {
        return new CreateAttachment();
    }

    /**
     * Create an instance of {@link MergeAppointment }
     * 
     */
    public MergeAppointment createMergeAppointment() {
        return new MergeAppointment();
    }

    /**
     * Create an instance of {@link DeleteAppointmentDeleteExceptionAsyncResponse }
     * 
     */
    public DeleteAppointmentDeleteExceptionAsyncResponse createDeleteAppointmentDeleteExceptionAsyncResponse() {
        return new DeleteAppointmentDeleteExceptionAsyncResponse();
    }

    /**
     * Create an instance of {@link FindActivityCategories }
     * 
     */
    public FindActivityCategories createFindActivityCategories() {
        return new FindActivityCategories();
    }

    /**
     * Create an instance of {@link CreateAttachmentAsync }
     * 
     */
    public CreateAttachmentAsync createCreateAttachmentAsync() {
        return new CreateAttachmentAsync();
    }

    /**
     * Create an instance of {@link DeleteAttachmentAsync }
     * 
     */
    public DeleteAttachmentAsync createDeleteAttachmentAsync() {
        return new DeleteAttachmentAsync();
    }

    /**
     * Create an instance of {@link CreateAppointmentDeleteException }
     * 
     */
    public CreateAppointmentDeleteException createCreateAppointmentDeleteException() {
        return new CreateAppointmentDeleteException();
    }

    /**
     * Create an instance of {@link FindNotesResponse }
     * 
     */
    public FindNotesResponse createFindNotesResponse() {
        return new FindNotesResponse();
    }

    /**
     * Create an instance of {@link FindActivityAssigneeAsync }
     * 
     */
    public FindActivityAssigneeAsync createFindActivityAssigneeAsync() {
        return new FindActivityAssigneeAsync();
    }

    /**
     * Create an instance of {@link CreateAttachmentResponse }
     * 
     */
    public CreateAttachmentResponse createCreateAttachmentResponse() {
        return new CreateAttachmentResponse();
    }

    /**
     * Create an instance of {@link DeleteActivityContactResponse }
     * 
     */
    public DeleteActivityContactResponse createDeleteActivityContactResponse() {
        return new DeleteActivityContactResponse();
    }

    /**
     * Create an instance of {@link UpdateActivityContactResponse }
     * 
     */
    public UpdateActivityContactResponse createUpdateActivityContactResponse() {
        return new UpdateActivityContactResponse();
    }

    /**
     * Create an instance of {@link GetActivityContactResponse }
     * 
     */
    public GetActivityContactResponse createGetActivityContactResponse() {
        return new GetActivityContactResponse();
    }

    /**
     * Create an instance of {@link UpdateActivityAssigneeResponse }
     * 
     */
    public UpdateActivityAssigneeResponse createUpdateActivityAssigneeResponse() {
        return new UpdateActivityAssigneeResponse();
    }

    /**
     * Create an instance of {@link GetAppointment }
     * 
     */
    public GetAppointment createGetAppointment() {
        return new GetAppointment();
    }

    /**
     * Create an instance of {@link DeleteAppointmentDeleteException }
     * 
     */
    public DeleteAppointmentDeleteException createDeleteAppointmentDeleteException() {
        return new DeleteAppointmentDeleteException();
    }

    /**
     * Create an instance of {@link GetAppointmentDeleteExceptionAsync }
     * 
     */
    public GetAppointmentDeleteExceptionAsync createGetAppointmentDeleteExceptionAsync() {
        return new GetAppointmentDeleteExceptionAsync();
    }

    /**
     * Create an instance of {@link FindNotes }
     * 
     */
    public FindNotes createFindNotes() {
        return new FindNotes();
    }

    /**
     * Create an instance of {@link DeleteNotesAsyncResponse }
     * 
     */
    public DeleteNotesAsyncResponse createDeleteNotesAsyncResponse() {
        return new DeleteNotesAsyncResponse();
    }

    /**
     * Create an instance of {@link CopyAttachment }
     * 
     */
    public CopyAttachment createCopyAttachment() {
        return new CopyAttachment();
    }

    /**
     * Create an instance of {@link CreateAppointment }
     * 
     */
    public CreateAppointment createCreateAppointment() {
        return new CreateAppointment();
    }

    /**
     * Create an instance of {@link GetAppointmentDeleteExceptionResponse }
     * 
     */
    public GetAppointmentDeleteExceptionResponse createGetAppointmentDeleteExceptionResponse() {
        return new GetAppointmentDeleteExceptionResponse();
    }

    /**
     * Create an instance of {@link GetNotes }
     * 
     */
    public GetNotes createGetNotes() {
        return new GetNotes();
    }

    /**
     * Create an instance of {@link UpdateActivityAssigneeAsyncResponse }
     * 
     */
    public UpdateActivityAssigneeAsyncResponse createUpdateActivityAssigneeAsyncResponse() {
        return new UpdateActivityAssigneeAsyncResponse();
    }

    /**
     * Create an instance of {@link DeleteActivityAssigneeAsync }
     * 
     */
    public DeleteActivityAssigneeAsync createDeleteActivityAssigneeAsync() {
        return new DeleteActivityAssigneeAsync();
    }

    /**
     * Create an instance of {@link CreateAppointmentAsyncResponse }
     * 
     */
    public CreateAppointmentAsyncResponse createCreateAppointmentAsyncResponse() {
        return new CreateAppointmentAsyncResponse();
    }

    /**
     * Create an instance of {@link UpdateNotes }
     * 
     */
    public UpdateNotes createUpdateNotes() {
        return new UpdateNotes();
    }

    /**
     * Create an instance of {@link GetActivityAssigneeResponse }
     * 
     */
    public GetActivityAssigneeResponse createGetActivityAssigneeResponse() {
        return new GetActivityAssigneeResponse();
    }

    /**
     * Create an instance of {@link DeleteNotesAsync }
     * 
     */
    public DeleteNotesAsync createDeleteNotesAsync() {
        return new DeleteNotesAsync();
    }

    /**
     * Create an instance of {@link FindActivityAssigneeResponse }
     * 
     */
    public FindActivityAssigneeResponse createFindActivityAssigneeResponse() {
        return new FindActivityAssigneeResponse();
    }

    /**
     * Create an instance of {@link UpdateActivityContactAsyncResponse }
     * 
     */
    public UpdateActivityContactAsyncResponse createUpdateActivityContactAsyncResponse() {
        return new UpdateActivityContactAsyncResponse();
    }

    /**
     * Create an instance of {@link DeleteAttachment }
     * 
     */
    public DeleteAttachment createDeleteAttachment() {
        return new DeleteAttachment();
    }

    /**
     * Create an instance of {@link DeleteActivityCategoriesAsync }
     * 
     */
    public DeleteActivityCategoriesAsync createDeleteActivityCategoriesAsync() {
        return new DeleteActivityCategoriesAsync();
    }

    /**
     * Create an instance of {@link DeleteAppointmentResponse }
     * 
     */
    public DeleteAppointmentResponse createDeleteAppointmentResponse() {
        return new DeleteAppointmentResponse();
    }

    /**
     * Create an instance of {@link UpdateAppointmentDeleteException }
     * 
     */
    public UpdateAppointmentDeleteException createUpdateAppointmentDeleteException() {
        return new UpdateAppointmentDeleteException();
    }

    /**
     * Create an instance of {@link CreateNotesAsync }
     * 
     */
    public CreateNotesAsync createCreateNotesAsync() {
        return new CreateNotesAsync();
    }

    /**
     * Create an instance of {@link UpdateActivityAssignee }
     * 
     */
    public UpdateActivityAssignee createUpdateActivityAssignee() {
        return new UpdateActivityAssignee();
    }

    /**
     * Create an instance of {@link GetAttachmentResponse }
     * 
     */
    public GetAttachmentResponse createGetAttachmentResponse() {
        return new GetAttachmentResponse();
    }

    /**
     * Create an instance of {@link FindActivityAssigneeAsyncResponse }
     * 
     */
    public FindActivityAssigneeAsyncResponse createFindActivityAssigneeAsyncResponse() {
        return new FindActivityAssigneeAsyncResponse();
    }

    /**
     * Create an instance of {@link DeleteAttachmentResponse }
     * 
     */
    public DeleteAttachmentResponse createDeleteAttachmentResponse() {
        return new DeleteAttachmentResponse();
    }

    /**
     * Create an instance of {@link UpdateAppointmentAsyncResponse }
     * 
     */
    public UpdateAppointmentAsyncResponse createUpdateAppointmentAsyncResponse() {
        return new UpdateAppointmentAsyncResponse();
    }

    /**
     * Create an instance of {@link UpdateActivityCategoriesAsyncResponse }
     * 
     */
    public UpdateActivityCategoriesAsyncResponse createUpdateActivityCategoriesAsyncResponse() {
        return new UpdateActivityCategoriesAsyncResponse();
    }

    /**
     * Create an instance of {@link CreateActivityAssigneeAsync }
     * 
     */
    public CreateActivityAssigneeAsync createCreateActivityAssigneeAsync() {
        return new CreateActivityAssigneeAsync();
    }

    /**
     * Create an instance of {@link DeleteActivityContact }
     * 
     */
    public DeleteActivityContact createDeleteActivityContact() {
        return new DeleteActivityContact();
    }

    /**
     * Create an instance of {@link CreateActivityCategoriesAsyncResponse }
     * 
     */
    public CreateActivityCategoriesAsyncResponse createCreateActivityCategoriesAsyncResponse() {
        return new CreateActivityCategoriesAsyncResponse();
    }

    /**
     * Create an instance of {@link UpdateActivityContactAsync }
     * 
     */
    public UpdateActivityContactAsync createUpdateActivityContactAsync() {
        return new UpdateActivityContactAsync();
    }

    /**
     * Create an instance of {@link CreateAttachmentAsyncResponse }
     * 
     */
    public CreateAttachmentAsyncResponse createCreateAttachmentAsyncResponse() {
        return new CreateAttachmentAsyncResponse();
    }

    /**
     * Create an instance of {@link GetNotesAsync }
     * 
     */
    public GetNotesAsync createGetNotesAsync() {
        return new GetNotesAsync();
    }

    /**
     * Create an instance of {@link FindActivityContactAsyncResponse }
     * 
     */
    public FindActivityContactAsyncResponse createFindActivityContactAsyncResponse() {
        return new FindActivityContactAsyncResponse();
    }

    /**
     * Create an instance of {@link CreateAppointmentDeleteExceptionAsyncResponse }
     * 
     */
    public CreateAppointmentDeleteExceptionAsyncResponse createCreateAppointmentDeleteExceptionAsyncResponse() {
        return new CreateAppointmentDeleteExceptionAsyncResponse();
    }

    /**
     * Create an instance of {@link DeleteAppointmentAsync }
     * 
     */
    public DeleteAppointmentAsync createDeleteAppointmentAsync() {
        return new DeleteAppointmentAsync();
    }

    /**
     * Create an instance of {@link GetAttachmentAsyncResponse }
     * 
     */
    public GetAttachmentAsyncResponse createGetAttachmentAsyncResponse() {
        return new GetAttachmentAsyncResponse();
    }

    /**
     * Create an instance of {@link FindActivityCategoriesAsyncResponse }
     * 
     */
    public FindActivityCategoriesAsyncResponse createFindActivityCategoriesAsyncResponse() {
        return new FindActivityCategoriesAsyncResponse();
    }

    /**
     * Create an instance of {@link CreateAppointmentDeleteExceptionAsync }
     * 
     */
    public CreateAppointmentDeleteExceptionAsync createCreateAppointmentDeleteExceptionAsync() {
        return new CreateAppointmentDeleteExceptionAsync();
    }

    /**
     * Create an instance of {@link GetActivityAssigneeAsyncResponse }
     * 
     */
    public GetActivityAssigneeAsyncResponse createGetActivityAssigneeAsyncResponse() {
        return new GetActivityAssigneeAsyncResponse();
    }

    /**
     * Create an instance of {@link FindAppointment }
     * 
     */
    public FindAppointment createFindAppointment() {
        return new FindAppointment();
    }

    /**
     * Create an instance of {@link FindActivityCategoriesResponse }
     * 
     */
    public FindActivityCategoriesResponse createFindActivityCategoriesResponse() {
        return new FindActivityCategoriesResponse();
    }

    /**
     * Create an instance of {@link DeleteAppointmentDeleteExceptionAsync }
     * 
     */
    public DeleteAppointmentDeleteExceptionAsync createDeleteAppointmentDeleteExceptionAsync() {
        return new DeleteAppointmentDeleteExceptionAsync();
    }

    /**
     * Create an instance of {@link CopyAttachmentAsync }
     * 
     */
    public CopyAttachmentAsync createCopyAttachmentAsync() {
        return new CopyAttachmentAsync();
    }

    /**
     * Create an instance of {@link CopyAttachmentResponse }
     * 
     */
    public CopyAttachmentResponse createCopyAttachmentResponse() {
        return new CopyAttachmentResponse();
    }

    /**
     * Create an instance of {@link GetNotesResponse }
     * 
     */
    public GetNotesResponse createGetNotesResponse() {
        return new GetNotesResponse();
    }

    /**
     * Create an instance of {@link CreateNotesAsyncResponse }
     * 
     */
    public CreateNotesAsyncResponse createCreateNotesAsyncResponse() {
        return new CreateNotesAsyncResponse();
    }

    /**
     * Create an instance of {@link DeleteActivityCategoriesResponse }
     * 
     */
    public DeleteActivityCategoriesResponse createDeleteActivityCategoriesResponse() {
        return new DeleteActivityCategoriesResponse();
    }

    /**
     * Create an instance of {@link GetActivityContact }
     * 
     */
    public GetActivityContact createGetActivityContact() {
        return new GetActivityContact();
    }

    /**
     * Create an instance of {@link UpdateActivityContact }
     * 
     */
    public UpdateActivityContact createUpdateActivityContact() {
        return new UpdateActivityContact();
    }

    /**
     * Create an instance of {@link FindNotesAsyncResponse }
     * 
     */
    public FindNotesAsyncResponse createFindNotesAsyncResponse() {
        return new FindNotesAsyncResponse();
    }

    /**
     * Create an instance of {@link GetNotesAsyncResponse }
     * 
     */
    public GetNotesAsyncResponse createGetNotesAsyncResponse() {
        return new GetNotesAsyncResponse();
    }

    /**
     * Create an instance of {@link DeleteAppointmentDeleteExceptionResponse }
     * 
     */
    public DeleteAppointmentDeleteExceptionResponse createDeleteAppointmentDeleteExceptionResponse() {
        return new DeleteAppointmentDeleteExceptionResponse();
    }

    /**
     * Create an instance of {@link FindActivityAssignee }
     * 
     */
    public FindActivityAssignee createFindActivityAssignee() {
        return new FindActivityAssignee();
    }

    /**
     * Create an instance of {@link GetActivityCategories }
     * 
     */
    public GetActivityCategories createGetActivityCategories() {
        return new GetActivityCategories();
    }

    /**
     * Create an instance of {@link CreateActivityContactResponse }
     * 
     */
    public CreateActivityContactResponse createCreateActivityContactResponse() {
        return new CreateActivityContactResponse();
    }

    /**
     * Create an instance of {@link CreateActivityAssigneeAsyncResponse }
     * 
     */
    public CreateActivityAssigneeAsyncResponse createCreateActivityAssigneeAsyncResponse() {
        return new CreateActivityAssigneeAsyncResponse();
    }

    /**
     * Create an instance of {@link FindAppointmentResponse }
     * 
     */
    public FindAppointmentResponse createFindAppointmentResponse() {
        return new FindAppointmentResponse();
    }

    /**
     * Create an instance of {@link FindActivityContactAsync }
     * 
     */
    public FindActivityContactAsync createFindActivityContactAsync() {
        return new FindActivityContactAsync();
    }

    /**
     * Create an instance of {@link FindActivityCategoriesAsync }
     * 
     */
    public FindActivityCategoriesAsync createFindActivityCategoriesAsync() {
        return new FindActivityCategoriesAsync();
    }

    /**
     * Create an instance of {@link DeleteActivityCategories }
     * 
     */
    public DeleteActivityCategories createDeleteActivityCategories() {
        return new DeleteActivityCategories();
    }

    /**
     * Create an instance of {@link FindActivityContact }
     * 
     */
    public FindActivityContact createFindActivityContact() {
        return new FindActivityContact();
    }

    /**
     * Create an instance of {@link CreateActivityAssigneeResponse }
     * 
     */
    public CreateActivityAssigneeResponse createCreateActivityAssigneeResponse() {
        return new CreateActivityAssigneeResponse();
    }

    /**
     * Create an instance of {@link DeleteActivityAssignee }
     * 
     */
    public DeleteActivityAssignee createDeleteActivityAssignee() {
        return new DeleteActivityAssignee();
    }

    /**
     * Create an instance of {@link FindActivityContactResponse }
     * 
     */
    public FindActivityContactResponse createFindActivityContactResponse() {
        return new FindActivityContactResponse();
    }

    /**
     * Create an instance of {@link GetAttachmentAsync }
     * 
     */
    public GetAttachmentAsync createGetAttachmentAsync() {
        return new GetAttachmentAsync();
    }

    /**
     * Create an instance of {@link GetActivityAssigneeAsync }
     * 
     */
    public GetActivityAssigneeAsync createGetActivityAssigneeAsync() {
        return new GetActivityAssigneeAsync();
    }

    /**
     * Create an instance of {@link GetActivityContactAsyncResponse }
     * 
     */
    public GetActivityContactAsyncResponse createGetActivityContactAsyncResponse() {
        return new GetActivityContactAsyncResponse();
    }

    /**
     * Create an instance of {@link CreateNotes }
     * 
     */
    public CreateNotes createCreateNotes() {
        return new CreateNotes();
    }

    /**
     * Create an instance of {@link UpdateAppointment }
     * 
     */
    public UpdateAppointment createUpdateAppointment() {
        return new UpdateAppointment();
    }

}
