package com.oracle.pts.custom.wsclient;

import javax.xml.ws.WebServiceRef;

import weblogic.wsee.jws.jaxws.owsm.SecurityPoliciesFeature;
// !THE CHANGES MADE TO THIS FILE WILL BE DESTROYED IF REGENERATED!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 111209.0821.28162)

public class CustomerCenterCustomObjectServiceSoapHttpPortClient
{
  @WebServiceRef
  private static CustomerCenterCustomObjectService_Service customerCenterCustomObjectService_Service;

  public static void main(String [] args)
  {
    customerCenterCustomObjectService_Service = new CustomerCenterCustomObjectService_Service();
        SecurityPoliciesFeature securityFeatures =
            new SecurityPoliciesFeature(new String[] { "oracle/wss_username_token_over_ssl_client_policy" });
        CustomerCenterCustomObjectService customerCenterCustomObjectService = customerCenterCustomObjectService_Service.getCustomerCenterCustomObjectServiceSoapHttpPort(securityFeatures);
        // Add your code to call the desired methods.
  }
}
