package com.oracle.pts.opp.wsclient;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebServiceClient(wsdlLocation="https://fap0930-crm.oracleads.com/opptyMgmtOpportunities/OpportunityService?WSDL",
  targetNamespace="http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/",
  name="OpportunityService")
public class OpportunityService_Service
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("com.oracle.pts.opp.wsclient.OpportunityService_Service");
      URL baseUrl = OpportunityService_Service.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            OpportunityService_Service.class.getResource("https://fap0930-crm.oracleads.com/opptyMgmtOpportunities/OpportunityService?WSDL");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "https://fap0930-crm.oracleads.com/opptyMgmtOpportunities/OpportunityService?WSDL");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, "https://fap0930-crm.oracleads.com/opptyMgmtOpportunities/OpportunityService?WSDL");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using https://fap0930-crm.oracleads.com/opptyMgmtOpportunities/OpportunityService?WSDL",
          e);
    }
  }

  public OpportunityService_Service()
  {
    super(wsdlLocationURL,
          new QName("http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/",
                    "OpportunityService"));
  }

  public OpportunityService_Service(URL wsdlLocation, QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="OpportunityServiceSoapHttpPort")
  public com.oracle.pts.opp.wsclient.OpportunityService getOpportunityServiceSoapHttpPort()
  {
    return (com.oracle.pts.opp.wsclient.OpportunityService) super.getPort(new QName("http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/",
                                                                                    "OpportunityServiceSoapHttpPort"),
                                                                          com.oracle.pts.opp.wsclient.OpportunityService.class);
  }

  @WebEndpoint(name="OpportunityServiceSoapHttpPort")
  public com.oracle.pts.opp.wsclient.OpportunityService getOpportunityServiceSoapHttpPort(WebServiceFeature... features)
  {
    return (com.oracle.pts.opp.wsclient.OpportunityService) super.getPort(new QName("http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/",
                                                                                    "OpportunityServiceSoapHttpPort"),
                                                                          com.oracle.pts.opp.wsclient.OpportunityService.class,
                                                                          features);
  }
}
