package com.oracle.ptsdemo.healthcare.model.am.client;

import com.oracle.ptsdemo.healthcare.model.am.common.HealthCarePrescriptionModelAM;

import com.oracle.ptsdemo.healthcare.wsclient.osc.opty.ServiceException;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jan 13 10:25:05 BRST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HealthCarePrescriptionModelAMClient extends ApplicationModuleImpl implements HealthCarePrescriptionModelAM {
    @SuppressWarnings("compatibility:6734801799526496173")
    private static final long serialVersionUID = -366318050385234310L;

    /**
     * This is the default constructor (do not remove).
     */
    public HealthCarePrescriptionModelAMClient() {
    }


    public void createAndInitPrescription(String visitId, String patientEmail,
                                          String doctorId, String patientId,
                                          String doctorName,
                                          String patientName) {
        Object _ret =
            this.riInvokeExportedMethod(this,"createAndInitPrescription",new String [] {"java.lang.String","java.lang.String","java.lang.String","java.lang.String","java.lang.String","java.lang.String"},new Object[] {visitId, patientEmail, doctorId, patientId, doctorName, patientName});
        return;
    }

    public void updateOSCFields(String patientId, String jwtToken) {
        Object _ret =
            this.riInvokeExportedMethod(this,"updateOSCFields",new String [] {"java.lang.String","java.lang.String"},new Object[] {patientId, jwtToken});
        return;
    }

    public void sendPrescriptionToPharmacy(String doctorName,
                                           String jwtToken) {
        Object _ret =
            this.riInvokeExportedMethod(this,"sendPrescriptionToPharmacy",new String [] {"java.lang.String","java.lang.String"},new Object[] {doctorName, jwtToken});
        return;
    }
}
