package com.oracle.ptsdemo.healthcare.wsclient.pharmacyload.wsclient;

import com.oracle.ptsdemo.healthcare.wsclient.pharmacyload.wsclient.generated.Medication;
import com.oracle.ptsdemo.healthcare.wsclient.pharmacyload.wsclient.generated.ObjectFactory;
import com.oracle.ptsdemo.healthcare.wsclient.pharmacyload.wsclient.generated.Prescription;

import java.util.List;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebService(wsdlLocation="https://jcs.my-oraclecloudapps.com/HealthCare/HealthCareLoadPort?WSDL",
  targetNamespace="http://ws.healthcare.ptsdemo.oracle.com/", name="HealthCareLoad")
@XmlSeeAlso(
  { ObjectFactory.class })
public interface HealthCareLoad
{
  @WebMethod
  @Action(input="http://ws.healthcare.ptsdemo.oracle.com/HealthCareLoad/createMedication")
  @RequestWrapper(localName="createMedication", targetNamespace="http://ws.healthcare.ptsdemo.oracle.com/",
    className="com.oracle.ptsdemo.healthcare.wsclient.pharmacyload.wsclient.generated.CreateMedication")
  @Oneway
  public void createMedication(@WebParam(targetNamespace="", name="arg0")
    String arg0, @WebParam(targetNamespace="", name="arg1")
    String arg1);

  @WebMethod
  @Action(input="http://ws.healthcare.ptsdemo.oracle.com/HealthCareLoad/createPrescriptionRequest",
    output="http://ws.healthcare.ptsdemo.oracle.com/HealthCareLoad/createPrescriptionResponse")
  @ResponseWrapper(localName="createPrescriptionResponse",
    targetNamespace="http://ws.healthcare.ptsdemo.oracle.com/", className="com.oracle.ptsdemo.healthcare.wsclient.pharmacyload.wsclient.generated.CreatePrescriptionResponse")
  @RequestWrapper(localName="createPrescription", targetNamespace="http://ws.healthcare.ptsdemo.oracle.com/",
    className="com.oracle.ptsdemo.healthcare.wsclient.pharmacyload.wsclient.generated.CreatePrescription")
  @WebResult(targetNamespace="")
  public String createPrescription(@WebParam(targetNamespace="", name="arg0")
    Prescription arg0);

  @WebMethod
  @Action(input="http://ws.healthcare.ptsdemo.oracle.com/HealthCareLoad/getMedicationListRequest",
    output="http://ws.healthcare.ptsdemo.oracle.com/HealthCareLoad/getMedicationListResponse")
  @ResponseWrapper(localName="getMedicationListResponse", targetNamespace="http://ws.healthcare.ptsdemo.oracle.com/",
    className="com.oracle.ptsdemo.healthcare.wsclient.pharmacyload.wsclient.generated.GetMedicationListResponse")
  @RequestWrapper(localName="getMedicationList", targetNamespace="http://ws.healthcare.ptsdemo.oracle.com/",
    className="com.oracle.ptsdemo.healthcare.wsclient.pharmacyload.wsclient.generated.GetMedicationList")
  @WebResult(targetNamespace="")
  public List<String> getMedicationList();

  @WebMethod
  @Action(input="http://ws.healthcare.ptsdemo.oracle.com/HealthCareLoad/getMedicationDetailListRequest",
    output="http://ws.healthcare.ptsdemo.oracle.com/HealthCareLoad/getMedicationDetailListResponse")
  @ResponseWrapper(localName="getMedicationDetailListResponse",
    targetNamespace="http://ws.healthcare.ptsdemo.oracle.com/", className="com.oracle.ptsdemo.healthcare.wsclient.pharmacyload.wsclient.generated.GetMedicationDetailListResponse")
  @RequestWrapper(localName="getMedicationDetailList", targetNamespace="http://ws.healthcare.ptsdemo.oracle.com/",
    className="com.oracle.ptsdemo.healthcare.wsclient.pharmacyload.wsclient.generated.GetMedicationDetailList")
  @WebResult(targetNamespace="")
  public List<Medication> getMedicationDetailList();
}
