//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FusionApplicationAccelerator.ServiceCatalogServiceReference {
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceDMLErrorMessage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceRowValErrorMessage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceAttrValErrorMessage))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/adf/svc/errors/")]
    public partial class ServiceErrorMessage : ServiceMessage {
        
        private object sdoObjectField;
        
        private string exceptionClassNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public object sdoObject {
            get {
                return this.sdoObjectField;
            }
            set {
                this.sdoObjectField = value;
                this.RaisePropertyChanged("sdoObject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string exceptionClassName {
            get {
                return this.exceptionClassNameField;
            }
            set {
                this.exceptionClassNameField = value;
                this.RaisePropertyChanged("exceptionClassName");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="commonj.sdo/java")]
    public partial class JavaInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string javaClassField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string javaClass {
            get {
                return this.javaClassField;
            }
            set {
                this.javaClassField = value;
                this.RaisePropertyChanged("javaClass");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="commonj.sdo")]
    public partial class ChangeSummaryType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlElement[] anyField;
        
        private string createField;
        
        private string deleteField;
        
        private bool loggingField;
        
        private bool loggingFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string create {
            get {
                return this.createField;
            }
            set {
                this.createField = value;
                this.RaisePropertyChanged("create");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string delete {
            get {
                return this.deleteField;
            }
            set {
                this.deleteField = value;
                this.RaisePropertyChanged("delete");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool logging {
            get {
                return this.loggingField;
            }
            set {
                this.loggingField = value;
                this.RaisePropertyChanged("logging");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool loggingSpecified {
            get {
                return this.loggingFieldSpecified;
            }
            set {
                this.loggingFieldSpecified = value;
                this.RaisePropertyChanged("loggingSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="commonj.sdo")]
    public partial class XSDType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="commonj.sdo")]
    public partial class ModelsType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DataGraphType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="commonj.sdo")]
    public abstract partial class BaseDataGraphType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ModelsType modelsField;
        
        private XSDType xsdField;
        
        private ChangeSummaryType changeSummaryField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ModelsType models {
            get {
                return this.modelsField;
            }
            set {
                this.modelsField = value;
                this.RaisePropertyChanged("models");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public XSDType xsd {
            get {
                return this.xsdField;
            }
            set {
                this.xsdField = value;
                this.RaisePropertyChanged("xsd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ChangeSummaryType changeSummary {
            get {
                return this.changeSummaryField;
            }
            set {
                this.changeSummaryField = value;
                this.RaisePropertyChanged("changeSummary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="commonj.sdo")]
    public partial class DataGraphType : BaseDataGraphType {
        
        private System.Xml.XmlElement anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="commonj.sdo")]
    public abstract partial class DataObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="commonj.sdo")]
    public partial class Property : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] aliasNameField;
        
        private System.Xml.XmlElement[] anyField;
        
        private string nameField;
        
        private bool manyField;
        
        private bool manyFieldSpecified;
        
        private bool containmentField;
        
        private bool containmentFieldSpecified;
        
        private string defaultField;
        
        private bool readOnlyField;
        
        private bool readOnlyFieldSpecified;
        
        private string typeField;
        
        private string oppositeField;
        
        private bool nullableField;
        
        private bool nullableFieldSpecified;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("aliasName", Order=0)]
        public string[] aliasName {
            get {
                return this.aliasNameField;
            }
            set {
                this.aliasNameField = value;
                this.RaisePropertyChanged("aliasName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=1)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool many {
            get {
                return this.manyField;
            }
            set {
                this.manyField = value;
                this.RaisePropertyChanged("many");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool manySpecified {
            get {
                return this.manyFieldSpecified;
            }
            set {
                this.manyFieldSpecified = value;
                this.RaisePropertyChanged("manySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool containment {
            get {
                return this.containmentField;
            }
            set {
                this.containmentField = value;
                this.RaisePropertyChanged("containment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool containmentSpecified {
            get {
                return this.containmentFieldSpecified;
            }
            set {
                this.containmentFieldSpecified = value;
                this.RaisePropertyChanged("containmentSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @default {
            get {
                return this.defaultField;
            }
            set {
                this.defaultField = value;
                this.RaisePropertyChanged("default");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool readOnly {
            get {
                return this.readOnlyField;
            }
            set {
                this.readOnlyField = value;
                this.RaisePropertyChanged("readOnly");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool readOnlySpecified {
            get {
                return this.readOnlyFieldSpecified;
            }
            set {
                this.readOnlyFieldSpecified = value;
                this.RaisePropertyChanged("readOnlySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string opposite {
            get {
                return this.oppositeField;
            }
            set {
                this.oppositeField = value;
                this.RaisePropertyChanged("opposite");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool nullable {
            get {
                return this.nullableField;
            }
            set {
                this.nullableField = value;
                this.RaisePropertyChanged("nullable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nullableSpecified {
            get {
                return this.nullableFieldSpecified;
            }
            set {
                this.nullableFieldSpecified = value;
                this.RaisePropertyChanged("nullableSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="commonj.sdo")]
    public partial class Type : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] baseTypeField;
        
        private Property[] propertyField;
        
        private string[] aliasNameField;
        
        private System.Xml.XmlElement[] anyField;
        
        private string nameField;
        
        private string uriField;
        
        private bool dataTypeField;
        
        private bool dataTypeFieldSpecified;
        
        private bool openField;
        
        private bool openFieldSpecified;
        
        private bool sequencedField;
        
        private bool sequencedFieldSpecified;
        
        private bool abstractField;
        
        private bool abstractFieldSpecified;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("baseType", DataType="anyURI", Order=0)]
        public string[] baseType {
            get {
                return this.baseTypeField;
            }
            set {
                this.baseTypeField = value;
                this.RaisePropertyChanged("baseType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("property", Order=1)]
        public Property[] property {
            get {
                return this.propertyField;
            }
            set {
                this.propertyField = value;
                this.RaisePropertyChanged("property");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("aliasName", Order=2)]
        public string[] aliasName {
            get {
                return this.aliasNameField;
            }
            set {
                this.aliasNameField = value;
                this.RaisePropertyChanged("aliasName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=3)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string uri {
            get {
                return this.uriField;
            }
            set {
                this.uriField = value;
                this.RaisePropertyChanged("uri");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool dataType {
            get {
                return this.dataTypeField;
            }
            set {
                this.dataTypeField = value;
                this.RaisePropertyChanged("dataType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataTypeSpecified {
            get {
                return this.dataTypeFieldSpecified;
            }
            set {
                this.dataTypeFieldSpecified = value;
                this.RaisePropertyChanged("dataTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool open {
            get {
                return this.openField;
            }
            set {
                this.openField = value;
                this.RaisePropertyChanged("open");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool openSpecified {
            get {
                return this.openFieldSpecified;
            }
            set {
                this.openFieldSpecified = value;
                this.RaisePropertyChanged("openSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool sequenced {
            get {
                return this.sequencedField;
            }
            set {
                this.sequencedField = value;
                this.RaisePropertyChanged("sequenced");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sequencedSpecified {
            get {
                return this.sequencedFieldSpecified;
            }
            set {
                this.sequencedFieldSpecified = value;
                this.RaisePropertyChanged("sequencedSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool @abstract {
            get {
                return this.abstractField;
            }
            set {
                this.abstractField = value;
                this.RaisePropertyChanged("abstract");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool abstractSpecified {
            get {
                return this.abstractFieldSpecified;
            }
            set {
                this.abstractFieldSpecified = value;
                this.RaisePropertyChanged("abstractSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceErrorMessage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceDMLErrorMessage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceRowValErrorMessage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceAttrValErrorMessage))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/adf/svc/errors/")]
    public partial class ServiceMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string messageField;
        
        private string severityField;
        
        private ServiceMessage[] detailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string severity {
            get {
                return this.severityField;
            }
            set {
                this.severityField = value;
                this.RaisePropertyChanged("severity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("detail", Order=3)]
        public ServiceMessage[] detail {
            get {
                return this.detailField;
            }
            set {
                this.detailField = value;
                this.RaisePropertyChanged("detail");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/oracle/apps/fnd/applcore/webservices/")]
    public partial class CatalogService : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string qNameField;
        
        private string lboField;
        
        private string lifecycleField;
        
        private string xsdLocationField;
        
        private string wsdlAddressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string qName {
            get {
                return this.qNameField;
            }
            set {
                this.qNameField = value;
                this.RaisePropertyChanged("qName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string lbo {
            get {
                return this.lboField;
            }
            set {
                this.lboField = value;
                this.RaisePropertyChanged("lbo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string lifecycle {
            get {
                return this.lifecycleField;
            }
            set {
                this.lifecycleField = value;
                this.RaisePropertyChanged("lifecycle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string xsdLocation {
            get {
                return this.xsdLocationField;
            }
            set {
                this.xsdLocationField = value;
                this.RaisePropertyChanged("xsdLocation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string wsdlAddress {
            get {
                return this.wsdlAddressField;
            }
            set {
                this.wsdlAddressField = value;
                this.RaisePropertyChanged("wsdlAddress");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/adf/svc/errors/")]
    public partial class ServiceDMLErrorMessage : ServiceErrorMessage {
        
        private string operationField;
        
        private string statementField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string operation {
            get {
                return this.operationField;
            }
            set {
                this.operationField = value;
                this.RaisePropertyChanged("operation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string statement {
            get {
                return this.statementField;
            }
            set {
                this.statementField = value;
                this.RaisePropertyChanged("statement");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/adf/svc/errors/")]
    public partial class ServiceRowValErrorMessage : ServiceErrorMessage {
        
        private string objectNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string objectName {
            get {
                return this.objectNameField;
            }
            set {
                this.objectNameField = value;
                this.RaisePropertyChanged("objectName");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/adf/svc/errors/")]
    public partial class ServiceAttrValErrorMessage : ServiceErrorMessage {
        
        private string attributeNameField;
        
        private string attributeValueField;
        
        private string objectNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string attributeName {
            get {
                return this.attributeNameField;
            }
            set {
                this.attributeNameField = value;
                this.RaisePropertyChanged("attributeName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string attributeValue {
            get {
                return this.attributeValueField;
            }
            set {
                this.attributeValueField = value;
                this.RaisePropertyChanged("attributeValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string objectName {
            get {
                return this.objectNameField;
            }
            set {
                this.objectNameField = value;
                this.RaisePropertyChanged("objectName");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://xmlns.oracle.com/oracle/apps/fnd/applcore/webservices/", ConfigurationName="ServiceCatalogServiceReference.ServiceCatalogService")]
    public interface ServiceCatalogService {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://xmlns.oracle.com/oracle/apps/fnd/applcore/webservices/types/) of message getAllServiceEndPointsRequest does not match the default value (http://xmlns.oracle.com/oracle/apps/fnd/applcore/webservices/)
        [System.ServiceModel.OperationContractAttribute(Action="http://xmlns.oracle.com/oracle/apps/fnd/applcore/webservices/getAllServiceEndPoin" +
            "ts", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(FusionApplicationAccelerator.ServiceCatalogServiceReference.ServiceErrorMessage), Action="http://xmlns.oracle.com/oracle/apps/fnd/applcore/webservices/getAllServiceEndPoin" +
            "ts", Name="ServiceErrorMessage", Namespace="http://xmlns.oracle.com/adf/svc/errors/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(JavaInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseDataGraphType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceMessage))]
        FusionApplicationAccelerator.ServiceCatalogServiceReference.getAllServiceEndPointsResponse getAllServiceEndPoints(FusionApplicationAccelerator.ServiceCatalogServiceReference.getAllServiceEndPointsRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://xmlns.oracle.com/oracle/apps/fnd/applcore/webservices/types/) of message getServiceEndPointRequest does not match the default value (http://xmlns.oracle.com/oracle/apps/fnd/applcore/webservices/)
        [System.ServiceModel.OperationContractAttribute(Action="http://xmlns.oracle.com/oracle/apps/fnd/applcore/webservices/getServiceEndPoint", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(FusionApplicationAccelerator.ServiceCatalogServiceReference.ServiceErrorMessage), Action="http://xmlns.oracle.com/oracle/apps/fnd/applcore/webservices/getServiceEndPoint", Name="ServiceErrorMessage", Namespace="http://xmlns.oracle.com/adf/svc/errors/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(JavaInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseDataGraphType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ServiceMessage))]
        FusionApplicationAccelerator.ServiceCatalogServiceReference.getServiceEndPointResponse getServiceEndPoint(FusionApplicationAccelerator.ServiceCatalogServiceReference.getServiceEndPointRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllServiceEndPoints", WrapperNamespace="http://xmlns.oracle.com/oracle/apps/fnd/applcore/webservices/types/", IsWrapped=true)]
    public partial class getAllServiceEndPointsRequest {
        
        public getAllServiceEndPointsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllServiceEndPointsResponse", WrapperNamespace="http://xmlns.oracle.com/oracle/apps/fnd/applcore/webservices/types/", IsWrapped=true)]
    public partial class getAllServiceEndPointsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/oracle/apps/fnd/applcore/webservices/types/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("result")]
        public CatalogService[] result;
        
        public getAllServiceEndPointsResponse() {
        }
        
        public getAllServiceEndPointsResponse(CatalogService[] result) {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getServiceEndPoint", WrapperNamespace="http://xmlns.oracle.com/oracle/apps/fnd/applcore/webservices/types/", IsWrapped=true)]
    public partial class getServiceEndPointRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/oracle/apps/fnd/applcore/webservices/types/", Order=0)]
        public string qname;
        
        public getServiceEndPointRequest() {
        }
        
        public getServiceEndPointRequest(string qname) {
            this.qname = qname;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getServiceEndPointResponse", WrapperNamespace="http://xmlns.oracle.com/oracle/apps/fnd/applcore/webservices/types/", IsWrapped=true)]
    public partial class getServiceEndPointResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/oracle/apps/fnd/applcore/webservices/types/", Order=0)]
        public FusionApplicationAccelerator.ServiceCatalogServiceReference.CatalogService result;
        
        public getServiceEndPointResponse() {
        }
        
        public getServiceEndPointResponse(FusionApplicationAccelerator.ServiceCatalogServiceReference.CatalogService result) {
            this.result = result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceCatalogServiceChannel : FusionApplicationAccelerator.ServiceCatalogServiceReference.ServiceCatalogService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceCatalogServiceClient : System.ServiceModel.ClientBase<FusionApplicationAccelerator.ServiceCatalogServiceReference.ServiceCatalogService>, FusionApplicationAccelerator.ServiceCatalogServiceReference.ServiceCatalogService {
        
        public ServiceCatalogServiceClient() {
        }
        
        public ServiceCatalogServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceCatalogServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCatalogServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCatalogServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FusionApplicationAccelerator.ServiceCatalogServiceReference.getAllServiceEndPointsResponse FusionApplicationAccelerator.ServiceCatalogServiceReference.ServiceCatalogService.getAllServiceEndPoints(FusionApplicationAccelerator.ServiceCatalogServiceReference.getAllServiceEndPointsRequest request) {
            return base.Channel.getAllServiceEndPoints(request);
        }
        
        public CatalogService[] getAllServiceEndPoints() {
            FusionApplicationAccelerator.ServiceCatalogServiceReference.getAllServiceEndPointsRequest inValue = new FusionApplicationAccelerator.ServiceCatalogServiceReference.getAllServiceEndPointsRequest();
            FusionApplicationAccelerator.ServiceCatalogServiceReference.getAllServiceEndPointsResponse retVal = ((FusionApplicationAccelerator.ServiceCatalogServiceReference.ServiceCatalogService)(this)).getAllServiceEndPoints(inValue);
            return retVal.result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FusionApplicationAccelerator.ServiceCatalogServiceReference.getServiceEndPointResponse FusionApplicationAccelerator.ServiceCatalogServiceReference.ServiceCatalogService.getServiceEndPoint(FusionApplicationAccelerator.ServiceCatalogServiceReference.getServiceEndPointRequest request) {
            return base.Channel.getServiceEndPoint(request);
        }
        
        public FusionApplicationAccelerator.ServiceCatalogServiceReference.CatalogService getServiceEndPoint(string qname) {
            FusionApplicationAccelerator.ServiceCatalogServiceReference.getServiceEndPointRequest inValue = new FusionApplicationAccelerator.ServiceCatalogServiceReference.getServiceEndPointRequest();
            inValue.qname = qname;
            FusionApplicationAccelerator.ServiceCatalogServiceReference.getServiceEndPointResponse retVal = ((FusionApplicationAccelerator.ServiceCatalogServiceReference.ServiceCatalogService)(this)).getServiceEndPoint(inValue);
            return retVal.result;
        }
    }
}
