package oracle.demo.pts.fusionservices.ActivityAppointment;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebServiceClient(wsdlLocation="https://dummy.oracle.com/appCmmnCompActivities/ActivityAppointmentService?wsdl",
  targetNamespace="http://xmlns.oracle.com/apps/crmCommon/activities/activitiesService/transient",
  name="ActivityAppointmentService")
public class ActivityAppointmentService_Service
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {logger = Logger.getLogger("oracle.demo.pts.fusionservices.ActivityAppointment.ActivityAppointmentService_Service");
      
   
    
  }

  public ActivityAppointmentService_Service()
  {
    super(wsdlLocationURL,
          new QName("http://xmlns.oracle.com/apps/crmCommon/activities/activitiesService/transient",
                    "ActivityAppointmentService"));
  }

  public ActivityAppointmentService_Service(URL wsdlLocation,
                                            QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="ActivityAppointmentServiceSoapHttpPort")
  public ActivityAppointmentService getActivityAppointmentServiceSoapHttpPort()
  {
    return (ActivityAppointmentService) super.getPort(new QName("http://xmlns.oracle.com/apps/crmCommon/activities/activitiesService/transient",
                                                                "ActivityAppointmentServiceSoapHttpPort"),
                                                      ActivityAppointmentService.class);
  }

  @WebEndpoint(name="ActivityAppointmentServiceSoapHttpPort")
  public ActivityAppointmentService getActivityAppointmentServiceSoapHttpPort(WebServiceFeature... features)
  {
    return (ActivityAppointmentService) super.getPort(new QName("http://xmlns.oracle.com/apps/crmCommon/activities/activitiesService/transient",
                                                                "ActivityAppointmentServiceSoapHttpPort"),
                                                      ActivityAppointmentService.class,
                                                      features);
  }
}
